In [1]:
import pandas as pd
import requests
pd.set_option('max_rows', 100)

In [2]:
url = 'https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-31-2020.csv'

### Get daily data from the url

In [3]:
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get(url, headers=header)
df = pd.read_html(r.text, header=[0], index_col=1)[0]

#### quick glance at the data

df[df.Country_Region=='US'].sort_values(by='Province_State')

In [4]:
df.describe()

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,0.0,2432.000000,2432.000000,2434.000000,2434.000000,2434.000000,2434.000000
mean,NaN,35.593296,-76.856383,352.295399,17.299507,73.144618,186.210764
std,NaN,11.408142,44.898252,3988.014789,329.031803,1470.015611,2672.700243
min,NaN,-42.882100,-159.596679,0.000000,0.000000,0.000000,-6.000000
25%,NaN,33.176592,-94.699320,2.000000,0.000000,0.000000,0.000000
50%,NaN,37.547916,-86.096751,6.000000,0.000000,0.000000,0.000000
75%,NaN,41.406791,-79.272587,31.000000,1.000000,0.000000,0.000000
max,NaN,71.706900,178.065000,105792.000000,12428.000000,63153.000000,77635.000000

### Aggregate by state

In [5]:
state_totals = df[df.Country_Region=='US'].groupby(by='Province_State').sum()

In [6]:
state_totals.describe()

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,58.0,58.000000,58.000000,58.000000,58.000000,58.000000,58.0
mean,0.0,1397.261622,-3327.747410,3244.344828,66.775862,121.103448,0.0
std,0.0,1154.954186,2887.627484,10179.628981,208.850660,922.296384,0.0
min,0.0,0.000000,-13378.805429,0.000000,0.000000,0.000000,0.0
25%,0.0,418.858961,-5190.570613,252.500000,4.250000,0.000000,0.0
50%,0.0,1152.194028,-3017.705127,659.500000,12.500000,0.000000,0.0
75%,0.0,2292.925088,-864.637952,2343.000000,52.750000,0.000000,0.0
max,0.0,4531.701456,145.673900,75833.000000,1550.000000,7024.000000,0.0

In [7]:
state_totals.sort_values(by='Confirmed', ascending=False)

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,0.0,2389.536539,-4229.693579,75833,1550,0,0
New Jersey,0.0,846.015259,-1567.071444,18696,267,0,0
California,0.0,1795.311328,-5787.848423,8210,173,0,0
Michigan,0.0,2971.190821,-5777.476718,7615,259,0,0
Florida,0.0,1583.394696,-4540.237308,6741,85,0,0
Massachusetts,0.0,548.293200,-930.501649,6620,89,0,0
Illinois,0.0,2134.881632,-4722.348891,5994,99,0,0
Washington,0.0,1608.118427,-4108.874073,5432,225,0,0
Louisiana,0.0,1863.156070,-5508.646964,5237,239,0,0
Pennsylvania,0.0,2446.615349,-4655.077407,4963,63,0,0
Georgia,0.0,4531.701456,-11543.485056,3929,111,0,0
Texas,0.0,4284.656829,-13378.805429,3809,54,0,0
Connecticut,0.0,332.909441,-581.254637,3128,69,0,0
Colorado,0.0,1951.034767,-5278.313545,2966,69,0,0
Tennessee,0.0,2904.830061,-6968.997577,2391,23,0,0
Ohio,0.0,2867.153059,-5882.648037,2199,55,0,0
Indiana,0.0,3191.320738,-6893.420638,2158,49,0,0
Maryland,0.0,858.280385,-1685.490893,1660,18,0,0
North Carolina,0.0,2884.451896,-6434.251094,1535,12,0,0
Wisconsin,0.0,2120.747855,-4301.680032,1412,25,0,0
Missouri,0.0,2566.059912,-6191.147734,1357,15,0,0
Arizona,0.0,505.138555,-1671.948482,1289,24,0,0
Virginia,0.0,3571.954933,-7425.653120,1249,27,0,0
Nevada,0.0,354.002394,-1058.069327,1114,26,0,0
South Carolina,0.0,1427.328311,-3398.818490,1083,22,0,0
Alabama,0.0,1950.187952,-5119.386303,987,23,0,0
Mississippi,0.0,2499.042518,-6814.580571,937,20,0,0
Utah,0.0,597.662127,-1674.823403,888,5,0,0
Oregon,0.0,1161.243425,-3165.475307,690,18,0,0
Minnesota,0.0,2345.606240,-4896.040014,629,12,0,0
Kentucky,0.0,2529.532903,-5720.720338,628,11,0,0
Oklahoma,0.0,1670.825272,-4547.619563,568,23,0,0
Arkansas,0.0,1778.171787,-4712.811994,523,8,0,0
Idaho,0.0,1143.144631,-2975.104203,515,8,0,0
Iowa,0.0,2349.538268,-5214.298717,497,7,0,0
District of Columbia,0.0,38.904178,-77.016560,495,9,0,0
Rhode Island,0.0,208.275711,-357.320525,488,8,0,0
Kansas,0.0,1574.194940,-3963.161229,434,9,0,0
New Hampshire,0.0,390.099096,-644.470235,357,3,0,0
Delaware,0.0,117.327830,-226.599712,319,10,0,0
New Mexico,0.0,624.758224,-1906.673850,315,4,0,0
Maine,0.0,532.891125,-838.483709,303,5,0,0
Vermont,0.0,528.707995,-872.548734,293,13,0,0
Puerto Rico,0.0,18.220800,-66.590100,239,8,0,0
Hawaii,0.0,83.962590,-629.657823,204,0,0,0
Montana,0.0,937.433138,-2232.635646,198,5,0,0
Nebraska,0.0,865.040765,-2058.268792,172,3,0,0
West Virginia,0.0,1092.247647,-2255.069480,162,1,0,0
North Dakota,0.0,1044.426761,-2213.193900,122,3,0,0
Alaska,0.0,362.539360,-862.001024,119,3,0,0
Wyoming,0.0,645.586196,-1608.302760,109,0,0,0
South Dakota,0.0,1366.640702,-3060.306051,108,1,0,0
Grand Princess,0.0,0.000000,0.000000,103,3,0,0
Guam,0.0,13.444300,144.793700,69,2,0,0
Diamond Princess,0.0,0.000000,0.000000,49,0,0,0
Virgin Islands,0.0,18.335800,-64.896300,30,0,0,0
Northern Mariana Islands,0.0,15.097900,145.673900,2,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,7024,0

In [8]:
state_totals.sort_values(by='Deaths', ascending=False)

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,0.0,2389.536539,-4229.693579,75833,1550,0,0
New Jersey,0.0,846.015259,-1567.071444,18696,267,0,0
Michigan,0.0,2971.190821,-5777.476718,7615,259,0,0
Louisiana,0.0,1863.156070,-5508.646964,5237,239,0,0
Washington,0.0,1608.118427,-4108.874073,5432,225,0,0
California,0.0,1795.311328,-5787.848423,8210,173,0,0
Georgia,0.0,4531.701456,-11543.485056,3929,111,0,0
Illinois,0.0,2134.881632,-4722.348891,5994,99,0,0
Massachusetts,0.0,548.293200,-930.501649,6620,89,0,0
Florida,0.0,1583.394696,-4540.237308,6741,85,0,0
Connecticut,0.0,332.909441,-581.254637,3128,69,0,0
Colorado,0.0,1951.034767,-5278.313545,2966,69,0,0
Pennsylvania,0.0,2446.615349,-4655.077407,4963,63,0,0
Ohio,0.0,2867.153059,-5882.648037,2199,55,0,0
Texas,0.0,4284.656829,-13378.805429,3809,54,0,0
Indiana,0.0,3191.320738,-6893.420638,2158,49,0,0
Virginia,0.0,3571.954933,-7425.653120,1249,27,0,0
Nevada,0.0,354.002394,-1058.069327,1114,26,0,0
Wisconsin,0.0,2120.747855,-4301.680032,1412,25,0,0
Arizona,0.0,505.138555,-1671.948482,1289,24,0,0
Tennessee,0.0,2904.830061,-6968.997577,2391,23,0,0
Alabama,0.0,1950.187952,-5119.386303,987,23,0,0
Oklahoma,0.0,1670.825272,-4547.619563,568,23,0,0
South Carolina,0.0,1427.328311,-3398.818490,1083,22,0,0
Mississippi,0.0,2499.042518,-6814.580571,937,20,0,0
Maryland,0.0,858.280385,-1685.490893,1660,18,0,0
Oregon,0.0,1161.243425,-3165.475307,690,18,0,0
Missouri,0.0,2566.059912,-6191.147734,1357,15,0,0
Vermont,0.0,528.707995,-872.548734,293,13,0,0
Minnesota,0.0,2345.606240,-4896.040014,629,12,0,0
North Carolina,0.0,2884.451896,-6434.251094,1535,12,0,0
Kentucky,0.0,2529.532903,-5720.720338,628,11,0,0
Delaware,0.0,117.327830,-226.599712,319,10,0,0
Kansas,0.0,1574.194940,-3963.161229,434,9,0,0
District of Columbia,0.0,38.904178,-77.016560,495,9,0,0
Idaho,0.0,1143.144631,-2975.104203,515,8,0,0
Rhode Island,0.0,208.275711,-357.320525,488,8,0,0
Puerto Rico,0.0,18.220800,-66.590100,239,8,0,0
Arkansas,0.0,1778.171787,-4712.811994,523,8,0,0
Iowa,0.0,2349.538268,-5214.298717,497,7,0,0
Utah,0.0,597.662127,-1674.823403,888,5,0,0
Montana,0.0,937.433138,-2232.635646,198,5,0,0
Maine,0.0,532.891125,-838.483709,303,5,0,0
New Mexico,0.0,624.758224,-1906.673850,315,4,0,0
North Dakota,0.0,1044.426761,-2213.193900,122,3,0,0
New Hampshire,0.0,390.099096,-644.470235,357,3,0,0
Nebraska,0.0,865.040765,-2058.268792,172,3,0,0
Alaska,0.0,362.539360,-862.001024,119,3,0,0
Grand Princess,0.0,0.000000,0.000000,103,3,0,0
Guam,0.0,13.444300,144.793700,69,2,0,0
South Dakota,0.0,1366.640702,-3060.306051,108,1,0,0
West Virginia,0.0,1092.247647,-2255.069480,162,1,0,0
Northern Mariana Islands,0.0,15.097900,145.673900,2,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,7024,0
Hawaii,0.0,83.962590,-629.657823,204,0,0,0
Virgin Islands,0.0,18.335800,-64.896300,30,0,0,0
Diamond Princess,0.0,0.000000,0.000000,49,0,0,0
Wyoming,0.0,645.586196,-1608.302760,109,0,0,0

In [9]:
df[df.Province_State=='New Jersey'].sort_values(by='Confirmed', ascending=False)

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
NaN,NaN,Unassigned,New Jersey,US,2020-03-31 23:43:56,0.000000,0.000000,3686,247,0,0,"Unassigned, New Jersey, US"
34003.0,NaN,Bergen,New Jersey,US,2020-03-31 23:43:56,40.960109,-74.071643,2909,4,0,0,"Bergen, New Jersey, US"
34013.0,NaN,Essex,New Jersey,US,2020-03-31 23:43:56,40.786813,-74.246580,1900,4,0,0,"Essex, New Jersey, US"
34017.0,NaN,Hudson,New Jersey,US,2020-03-31 23:43:56,40.737662,-74.075157,1606,2,0,0,"Hudson, New Jersey, US"
34039.0,NaN,Union,New Jersey,US,2020-03-31 23:43:56,40.658354,-74.306801,1418,0,0,0,"Union, New Jersey, US"
34031.0,NaN,Passaic,New Jersey,US,2020-03-31 23:43:56,41.032386,-74.299541,1294,1,0,0,"Passaic, New Jersey, US"
34023.0,NaN,Middlesex,New Jersey,US,2020-03-31 23:43:56,40.436299,-74.414270,1277,0,0,0,"Middlesex, New Jersey, US"
34025.0,NaN,Monmouth,New Jersey,US,2020-03-31 23:43:56,40.265497,-74.222407,1140,2,0,0,"Monmouth, New Jersey, US"
34029.0,NaN,Ocean,New Jersey,US,2020-03-31 23:43:56,39.889545,-74.280893,1022,1,0,0,"Ocean, New Jersey, US"
34027.0,NaN,Morris,New Jersey,US,2020-03-31 23:43:56,40.860953,-74.545537,841,1,0,0,"Morris, New Jersey, US"
34035.0,NaN,Somerset,New Jersey,US,2020-03-31 23:43:56,40.564657,-74.616830,413,1,0,0,"Somerset, New Jersey, US"
34021.0,NaN,Mercer,New Jersey,US,2020-03-31 23:43:56,40.280470,-74.704796,268,0,0,0,"Mercer, New Jersey, US"
34007.0,NaN,Camden,New Jersey,US,2020-03-31 23:43:56,39.803438,-74.963888,228,3,0,0,"Camden, New Jersey, US"
34005.0,NaN,Burlington,New Jersey,US,2020-03-31 23:43:56,39.876811,-74.669278,202,0,0,0,"Burlington, New Jersey, US"
34037.0,NaN,Sussex,New Jersey,US,2020-03-31 23:43:56,41.138916,-74.691182,132,0,0,0,"Sussex, New Jersey, US"
34015.0,NaN,Gloucester,New Jersey,US,2020-03-31 23:43:56,39.715811,-75.139955,114,0,0,0,"Gloucester, New Jersey, US"
34019.0,NaN,Hunterdon,New Jersey,US,2020-03-31 23:43:56,40.563352,-74.912842,97,0,0,0,"Hunterdon, New Jersey, US"
34041.0,NaN,Warren,New Jersey,US,2020-03-31 23:43:56,40.859518,-74.995565,76,0,0,0,"Warren, New Jersey, US"
34001.0,NaN,Atlantic,New Jersey,US,2020-03-31 23:43:56,39.475387,-74.658485,31,0,0,0,"Atlantic, New Jersey, US"
34011.0,NaN,Cumberland,New Jersey,US,2020-03-31 23:43:56,39.371994,-75.107126,18,1,0,0,"Cumberland, New Jersey, US"
34033.0,NaN,Salem,New Jersey,US,2020-03-31 23:43:56,39.587197,-75.346966,12,0,0,0,"Salem, New Jersey, US"
34009.0,NaN,Cape May,New Jersey,US,2020-03-31 23:43:56,39.150088,-74.801702,12,0,0,0,"Cape May, New Jersey, US"

In [10]:
df[df.Province_State=='New Jersey'].sort_values(by='Deaths', ascending=False)

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
NaN,NaN,Unassigned,New Jersey,US,2020-03-31 23:43:56,0.000000,0.000000,3686,247,0,0,"Unassigned, New Jersey, US"
34013.0,NaN,Essex,New Jersey,US,2020-03-31 23:43:56,40.786813,-74.246580,1900,4,0,0,"Essex, New Jersey, US"
34003.0,NaN,Bergen,New Jersey,US,2020-03-31 23:43:56,40.960109,-74.071643,2909,4,0,0,"Bergen, New Jersey, US"
34007.0,NaN,Camden,New Jersey,US,2020-03-31 23:43:56,39.803438,-74.963888,228,3,0,0,"Camden, New Jersey, US"
34017.0,NaN,Hudson,New Jersey,US,2020-03-31 23:43:56,40.737662,-74.075157,1606,2,0,0,"Hudson, New Jersey, US"
34025.0,NaN,Monmouth,New Jersey,US,2020-03-31 23:43:56,40.265497,-74.222407,1140,2,0,0,"Monmouth, New Jersey, US"
34031.0,NaN,Passaic,New Jersey,US,2020-03-31 23:43:56,41.032386,-74.299541,1294,1,0,0,"Passaic, New Jersey, US"
34011.0,NaN,Cumberland,New Jersey,US,2020-03-31 23:43:56,39.371994,-75.107126,18,1,0,0,"Cumberland, New Jersey, US"
34035.0,NaN,Somerset,New Jersey,US,2020-03-31 23:43:56,40.564657,-74.616830,413,1,0,0,"Somerset, New Jersey, US"
34027.0,NaN,Morris,New Jersey,US,2020-03-31 23:43:56,40.860953,-74.545537,841,1,0,0,"Morris, New Jersey, US"
34029.0,NaN,Ocean,New Jersey,US,2020-03-31 23:43:56,39.889545,-74.280893,1022,1,0,0,"Ocean, New Jersey, US"
34001.0,NaN,Atlantic,New Jersey,US,2020-03-31 23:43:56,39.475387,-74.658485,31,0,0,0,"Atlantic, New Jersey, US"
34039.0,NaN,Union,New Jersey,US,2020-03-31 23:43:56,40.658354,-74.306801,1418,0,0,0,"Union, New Jersey, US"
34037.0,NaN,Sussex,New Jersey,US,2020-03-31 23:43:56,41.138916,-74.691182,132,0,0,0,"Sussex, New Jersey, US"
34033.0,NaN,Salem,New Jersey,US,2020-03-31 23:43:56,39.587197,-75.346966,12,0,0,0,"Salem, New Jersey, US"
34023.0,NaN,Middlesex,New Jersey,US,2020-03-31 23:43:56,40.436299,-74.414270,1277,0,0,0,"Middlesex, New Jersey, US"
34021.0,NaN,Mercer,New Jersey,US,2020-03-31 23:43:56,40.280470,-74.704796,268,0,0,0,"Mercer, New Jersey, US"
34019.0,NaN,Hunterdon,New Jersey,US,2020-03-31 23:43:56,40.563352,-74.912842,97,0,0,0,"Hunterdon, New Jersey, US"
34015.0,NaN,Gloucester,New Jersey,US,2020-03-31 23:43:56,39.715811,-75.139955,114,0,0,0,"Gloucester, New Jersey, US"
34009.0,NaN,Cape May,New Jersey,US,2020-03-31 23:43:56,39.150088,-74.801702,12,0,0,0,"Cape May, New Jersey, US"
34005.0,NaN,Burlington,New Jersey,US,2020-03-31 23:43:56,39.876811,-74.669278,202,0,0,0,"Burlington, New Jersey, US"
34041.0,NaN,Warren,New Jersey,US,2020-03-31 23:43:56,40.859518,-74.995565,76,0,0,0,"Warren, New Jersey, US"

In [11]:
df[df.Province_State=='New York'].sort_values(by='Confirmed', ascending=False)

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
36061.0,NaN,New York City,New York,US,2020-03-31 23:43:56,40.767273,-73.971526,43119,932,0,0,"New York City, New York, US"
36119.0,NaN,Westchester,New York,US,2020-03-31 23:43:56,41.162784,-73.757417,9967,10,0,0,"Westchester, New York, US"
36059.0,NaN,Nassau,New York,US,2020-03-31 23:43:56,40.740665,-73.589419,8544,48,0,0,"Nassau, New York, US"
36103.0,NaN,Suffolk,New York,US,2020-03-31 23:43:56,40.883201,-72.801217,6713,44,0,0,"Suffolk, New York, US"
36087.0,NaN,Rockland,New York,US,2020-03-31 23:43:56,41.150279,-74.025605,2863,8,0,0,"Rockland, New York, US"
36071.0,NaN,Orange,New York,US,2020-03-31 23:43:56,41.403375,-74.302408,1556,5,0,0,"Orange, New York, US"
36029.0,NaN,Erie,New York,US,2020-03-31 23:43:56,42.762490,-78.730637,499,8,0,0,"Erie, New York, US"
36027.0,NaN,Dutchess,New York,US,2020-03-31 23:43:56,41.764861,-73.743567,484,3,0,0,"Dutchess, New York, US"
36055.0,NaN,Monroe,New York,US,2020-03-31 23:43:56,43.146389,-77.693229,257,8,0,0,"Monroe, New York, US"
36067.0,NaN,Onondaga,New York,US,2020-03-31 23:43:56,43.004919,-76.199712,249,1,0,0,"Onondaga, New York, US"
36001.0,NaN,Albany,New York,US,2020-03-31 23:43:56,42.600603,-73.977239,226,1,0,0,"Albany, New York, US"
36111.0,NaN,Ulster,New York,US,2020-03-31 23:43:56,41.890279,-74.262521,207,0,0,0,"Ulster, New York, US"
36079.0,NaN,Putnam,New York,US,2020-03-31 23:43:56,41.426301,-73.749655,167,0,0,0,"Putnam, New York, US"
36091.0,NaN,Saratoga,New York,US,2020-03-31 23:43:56,43.109042,-73.866539,108,1,0,0,"Saratoga, New York, US"
36105.0,NaN,Sullivan,New York,US,2020-03-31 23:43:56,41.715795,-74.763946,106,1,0,0,"Sullivan, New York, US"
36093.0,NaN,Schenectady,New York,US,2020-03-31 23:43:56,42.816688,-74.052783,85,1,0,0,"Schenectady, New York, US"
36109.0,NaN,Tompkins,New York,US,2020-03-31 23:43:56,42.449458,-76.472298,73,0,0,0,"Tompkins, New York, US"
36083.0,NaN,Rensselaer,New York,US,2020-03-31 23:43:56,42.713481,-73.510899,54,0,0,0,"Rensselaer, New York, US"
36053.0,NaN,Madison,New York,US,2020-03-31 23:43:56,42.916539,-75.672666,49,1,0,0,"Madison, New York, US"
36063.0,NaN,Niagara,New York,US,2020-03-31 23:43:56,43.198980,-78.747774,41,0,0,0,"Niagara, New York, US"
36007.0,NaN,Broome,New York,US,2020-03-31 23:43:56,42.159032,-75.813261,38,3,0,0,"Broome, New York, US"
36021.0,NaN,Columbia,New York,US,2020-03-31 23:43:56,42.248193,-73.630891,36,1,0,0,"Columbia, New York, US"
36065.0,NaN,Oneida,New York,US,2020-03-31 23:43:56,43.243754,-75.437104,34,0,0,0,"Oneida, New York, US"
36089.0,NaN,St. Lawrence,New York,US,2020-03-31 23:43:56,44.497618,-75.065500,23,0,0,0,"St. Lawrence, New York, US"
36019.0,NaN,Clinton,New York,US,2020-03-31 23:43:56,44.745309,-73.678754,21,0,0,0,"Clinton, New York, US"
36015.0,NaN,Chemung,New York,US,2020-03-31 23:43:56,42.138911,-76.763880,20,0,0,0,"Chemung, New York, US"
36069.0,NaN,Ontario,New York,US,2020-03-31 23:43:56,42.851457,-77.308744,20,0,0,0,"Ontario, New York, US"
36017.0,NaN,Chenango,New York,US,2020-03-31 23:43:56,42.494300,-75.608876,19,0,0,0,"Chenango, New York, US"
36101.0,NaN,Steuben,New York,US,2020-03-31 23:43:56,42.268914,-77.382992,19,0,0,0,"Steuben, New York, US"
36113.0,NaN,Warren,New York,US,2020-03-31 23:43:56,43.561730,-73.843370,18,0,0,0,"Warren, New York, US"
36077.0,NaN,Otsego,New York,US,2020-03-31 23:43:56,42.634926,-75.031514,17,1,0,0,"Otsego, New York, US"
36025.0,NaN,Delaware,New York,US,2020-03-31 23:43:56,42.198376,-74.967093,16,0,0,0,"Delaware, New York, US"
36051.0,NaN,Livingston,New York,US,2020-03-31 23:43:56,42.725963,-77.779662,15,0,0,0,"Livingston, New York, US"
36075.0,NaN,Oswego,New York,US,2020-03-31 23:43:56,43.427789,-76.146352,15,0,0,0,"Oswego, New York, US"
36117.0,NaN,Wayne,New York,US,2020-03-31 23:43:56,43.154944,-77.029765,15,0,0,0,"Wayne, New York, US"
36043.0,NaN,Herkimer,New York,US,2020-03-31 23:43:56,43.420342,-74.961453,12,2,0,0,"Herkimer, New York, US"
36045.0,NaN,Jefferson,New York,US,2020-03-31 23:43:56,44.042010,-75.946535,11,0,0,0,"Jefferson, New York, US"
36037.0,NaN,Genesee,New York,US,2020-03-31 23:43:56,43.002260,-78.191352,11,1,0,0,"Genesee, New York, US"
36023.0,NaN,Cortland,New York,US,2020-03-31 23:43:56,42.595092,-76.070489,10,0,0,0,"Cortland, New York, US"
36039.0,NaN,Greene,New York,US,2020-03-31 23:43:56,42.275797,-74.123849,10,0,0,0,"Greene, New York, US"
36003.0,NaN,Allegany,New York,US,2020-03-31 23:43:56,42.257484,-78.027505,9,1,0,0,"Allegany, New York, US"
36115.0,NaN,Washington,New York,US,2020-03-31 23:43:56,43.311538,-73.430434,9,0,0,0,"Washington, New York, US"
36107.0,NaN,Tioga,New York,US,2020-03-31 23:43:56,42.168528,-76.308358,8,0,0,0,"Tioga, New York, US"
36121.0,NaN,Wyoming,New York,US,2020-03-31 23:43:56,42.701451,-78.221996,8,1,0,0,"Wyoming, New York, US"
36013.0,NaN,Chautauqua,New York,US,2020-03-31 23:43:56,42.227692,-79.366918,7,0,0,0,"Chautauqua, New York, US"
36095.0,NaN,Schoharie,New York,US,2020-03-31 23:43:56,42.588317,-74.443390,6,0,0,0,"Schoharie, New York, US"
36009.0,NaN,Cattaraugus,New York,US,2020-03-31 23:43:56,42.247782,-78.679231,6,0,0,0,"Cattaraugus, New York, US"
36057.0,NaN,Montgomery,New York,US,2020-03-31 23:43:56,42.901235,-74.440116,6,0,0,0,"Montgomery, New York, US"
36033.0,NaN,Franklin,New York,US,2020-03-31 23:43:56,44.590409,-74.299260,6,0,0,0,"Franklin, New York, US"
36031.0,NaN,Essex,New York,US,2020-03-31 23:43:56,44.116308,-73.772978,5,0,0,0,"Essex, New York, US"
36073.0,NaN,Orleans,New York,US,2020-03-31 23:43:56,43.251698,-78.232007,5,0,0,0,"Orleans, New York, US"
36011.0,NaN,Cayuga,New York,US,2020-03-31 23:43:56,42.912617,-76.557316,4,0,0,0,"Cayuga, New York, US"
36097.0,NaN,Schuyler,New York,US,2020-03-31 23:43:56,42.391840,-76.877330,2,0,0,0,"Schuyler, New York, US"
36049.0,NaN,Lewis,New York,US,2020-03-31 23:43:56,43.784416,-75.449040,2,0,0,0,"Lewis, New York, US"
36041.0,NaN,Hamilton,New York,US,2020-03-31 23:43:56,43.661466,-74.497220,2,0,0,0,"Hamilton, New York, US"
36035.0,NaN,Fulton,New York,US,2020-03-31 23:43:56,43.113639,-74.417988,1,0,0,0,"Fulton, New York, US"
NaN,NaN,Unassigned,New York,US,2020-03-31 23:43:56,0.000000,0.000000,0,468,0,0,"Unassigned, New York, US"

In [12]:
df[df.Province_State=='New Hampshire'].sort_values(by='Confirmed', ascending=False)

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
33015.0,NaN,Rockingham,New Hampshire,US,2020-03-31 23:43:56,42.984997,-71.128834,137,1,0,0,"Rockingham, New Hampshire, US"
33011.0,NaN,Hillsborough,New Hampshire,US,2020-03-31 23:43:56,42.915378,-71.720025,99,2,0,0,"Hillsborough, New Hampshire, US"
33009.0,NaN,Grafton,New Hampshire,US,2020-03-31 23:43:56,43.937798,-71.820572,34,0,0,0,"Grafton, New Hampshire, US"
33017.0,NaN,Strafford,New Hampshire,US,2020-03-31 23:43:56,43.291833,-71.023360,28,0,0,0,"Strafford, New Hampshire, US"
33013.0,NaN,Merrimack,New Hampshire,US,2020-03-31 23:43:56,43.296630,-71.681157,27,0,0,0,"Merrimack, New Hampshire, US"
33001.0,NaN,Belknap,New Hampshire,US,2020-03-31 23:43:56,43.516373,-71.416842,12,0,0,0,"Belknap, New Hampshire, US"
33003.0,NaN,Carroll,New Hampshire,US,2020-03-31 23:43:56,43.874986,-71.204302,12,0,0,0,"Carroll, New Hampshire, US"
33005.0,NaN,Cheshire,New Hampshire,US,2020-03-31 23:43:56,42.920160,-72.253110,4,0,0,0,"Cheshire, New Hampshire, US"
33019.0,NaN,Sullivan,New Hampshire,US,2020-03-31 23:43:56,43.360941,-72.222031,4,0,0,0,"Sullivan, New Hampshire, US"
NaN,NaN,Unassigned,New Hampshire,US,2020-03-31 23:43:56,0.000000,0.000000,0,0,0,0,"Unassigned, New Hampshire, US"

In [13]:
population = pd.read_csv('data/SCPRC-EST2019-18+POP-RES.csv')
population.sort_values(by='POPESTIMATE2019', ascending=False).head(10)

,SUMLEV,REGION,DIVISION,STATE,NAME,POPESTIMATE2019,POPEST18PLUS2019,PCNT_POPEST18PLUS
0,10,0,0,0,United States,328239523,255200373,77.7
5,40,4,9,6,California,39512223,30617582,77.5
44,40,3,7,48,Texas,28995881,21596071,74.5
10,40,3,5,12,Florida,21477737,17247808,80.3
33,40,1,2,36,New York,19453561,15425262,79.3
39,40,1,2,42,Pennsylvania,12801989,10167376,79.4
14,40,2,3,17,Illinois,12671821,9853946,77.8
36,40,2,3,39,Ohio,11689100,9111081,77.9
11,40,3,5,13,Georgia,10617423,8113542,76.4
34,40,3,5,37,North Carolina,10488084,8187369,78.1

In [14]:
geog = pd.read_csv('data/us_geography.csv')
geog.head(10)

,State,tot_sq_mi,tot_sq_km,land_sq_mi,land_sq_km,water_sq_mi,water_sq_km,inland_sq_mi,inland_sq_km,coast_sq_mi,coast_sq_km,gl_sq_mi,gl_sq_km,terr_sq_mi,terr_sq_km,latitude,longitude
0,United States,"3,796,742","9,833,517","3,531,905","9,147,593","264,837","685,924","85,647","221,824","42,337","109,652","60,094","155,643","76,759","198,806",NaN,NaN
1,Alabama,"52,420","135,767","50,645","131,171","1,775","4,597","1,058","2,740",517,"1,340",—,—,199,516,32.739632,-86.843459
2,Alaska,"665,384","1,723,337","570,641","1,477,953","94,743","245,383","19,304","49,997","26,119","67,647",—,—,"49,320","127,739",63.346191,-152.837068
3,Arizona,"113,990","295,234","113,594","294,207",396,"1,026",396,"1,026",—,—,—,—,—,—,34.209964,-111.602401
4,Arkansas,"53,179","137,732","52,035","134,771","1,143","2,961","1,143","2,961",—,—,—,—,—,—,34.895526,-92.444626
5,California,"163,695","423,967","155,779","403,466","7,916","20,501","2,833","7,339",245,634,—,—,"4,837","12,528",37.148573,-119.540651
6,Colorado,"104,094","269,601","103,642","268,431",452,"1,170",452,"1,170",—,—,—,—,—,—,38.993575,-105.507774
7,Connecticut,"5,543","14,357","4,842","12,542",701,"1,816",171,443,530,"1,372",—,—,—,—,41.579784,-72.746667
8,Delaware,"2,489","6,446","1,949","5,047",540,"1,399",91,237,355,920,—,—,94,242,38.993550,-75.447374
9,District of Columbia,68,177,61,158,7,19,7,19,—,—,—,—,—,—,38.904148,-77.017094

population[['NAME', 'POPESTIMATE2019']]

### Merge state population date with state COVID-19 data

In [15]:
state_columns=['Confirmed', 'Deaths', 'Recovered', 'Active', ]

In [16]:
state_with_population = pd.merge(state_totals[state_columns], population[['NAME', 'POPESTIMATE2019']], left_on='Province_State', right_on='NAME')
state_with_population['fraction_confirmed'] = state_with_population['Confirmed'] / state_with_population['POPESTIMATE2019'] * 100.0
state_with_population['deaths'] = state_with_population['Deaths'] / state_with_population['POPESTIMATE2019'] * 100.0
state_with_population['death_rate?'] = state_with_population['Deaths'] / state_with_population['Confirmed'] * 100.0

In [17]:
state_with_population.sort_values(by='death_rate?', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
18,5237,239,0,0,Louisiana,4648794,0.112653,0.005141,4.563681
45,293,13,0,0,Vermont,623989,0.046956,0.002083,4.436860
47,5432,225,0,0,Washington,7614893,0.071334,0.002955,4.142121
36,568,23,0,0,Oklahoma,3956971,0.014354,0.000581,4.049296
22,7615,259,0,0,Michigan,9986857,0.076250,0.002593,3.401182
7,319,10,0,0,Delaware,973764,0.032759,0.001027,3.134796
10,3929,111,0,0,Georgia,10617423,0.037005,0.001045,2.825146
37,690,18,0,0,Oregon,4217737,0.016359,0.000427,2.608696
26,198,5,0,0,Montana,1068778,0.018526,0.000468,2.525253
1,119,3,0,0,Alaska,731545,0.016267,0.000410,2.521008
35,2199,55,0,0,Ohio,11689100,0.018812,0.000471,2.501137
34,122,3,0,0,North Dakota,762062,0.016009,0.000394,2.459016
28,1114,26,0,0,Nevada,3080156,0.036167,0.000844,2.333932
0,987,23,0,0,Alabama,4903185,0.020130,0.000469,2.330294
5,2966,69,0,0,Colorado,5758736,0.051504,0.001198,2.326365
14,2158,49,0,0,Indiana,6732219,0.032055,0.000728,2.270621
6,3128,69,0,0,Connecticut,3565287,0.087735,0.001935,2.205882
46,1249,27,0,0,Virginia,8535519,0.014633,0.000316,2.161729
24,937,20,0,0,Mississippi,2976149,0.031484,0.000672,2.134472
4,8210,173,0,0,California,39512223,0.020778,0.000438,2.107186
16,434,9,0,0,Kansas,2913314,0.014897,0.000309,2.073733
32,75833,1550,0,0,New York,19453561,0.389816,0.007968,2.043965
40,1083,22,0,0,South Carolina,5148714,0.021034,0.000427,2.031394
23,629,12,0,0,Minnesota,5639632,0.011153,0.000213,1.907790
2,1289,24,0,0,Arizona,7278717,0.017709,0.000330,1.861908
8,495,9,0,0,District of Columbia,705749,0.070138,0.001275,1.818182
49,1412,25,0,0,Wisconsin,5822434,0.024251,0.000429,1.770538
17,628,11,0,0,Kentucky,4467673,0.014057,0.000246,1.751592
27,172,3,0,0,Nebraska,1934408,0.008892,0.000155,1.744186
13,5994,99,0,0,Illinois,12671821,0.047302,0.000781,1.651652
19,303,5,0,0,Maine,1344212,0.022541,0.000372,1.650165
39,488,8,0,0,Rhode Island,1059361,0.046066,0.000755,1.639344
12,515,8,0,0,Idaho,1787065,0.028818,0.000448,1.553398
3,523,8,0,0,Arkansas,3017804,0.017330,0.000265,1.529637
30,18696,267,0,0,New Jersey,8882190,0.210489,0.003006,1.428113
43,3809,54,0,0,Texas,28995881,0.013136,0.000186,1.417695
15,497,7,0,0,Iowa,3155070,0.015752,0.000222,1.408451
21,6620,89,0,0,Massachusetts,6892503,0.096046,0.001291,1.344411
31,315,4,0,0,New Mexico,2096829,0.015023,0.000191,1.269841
38,4963,63,0,0,Pennsylvania,12801989,0.038767,0.000492,1.269394
9,6741,85,0,0,Florida,21477737,0.031386,0.000396,1.260941
25,1357,15,0,0,Missouri,6137428,0.022110,0.000244,1.105380
20,1660,18,0,0,Maryland,6045680,0.027458,0.000298,1.084337
42,2391,23,0,0,Tennessee,6829174,0.035012,0.000337,0.961941
41,108,1,0,0,South Dakota,884659,0.012208,0.000113,0.925926
29,357,3,0,0,New Hampshire,1359711,0.026256,0.000221,0.840336
33,1535,12,0,0,North Carolina,10488084,0.014636,0.000114,0.781759
48,162,1,0,0,West Virginia,1792147,0.009039,0.000056,0.617284
44,888,5,0,0,Utah,3205958,0.027698,0.000156,0.563063
11,204,0,0,0,Hawaii,1415872,0.014408,0.000000,0.000000
50,109,0,0,0,Wyoming,578759,0.018833,0.000000,0.000000

In [18]:
state_with_population.sort_values(by='fraction_confirmed', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
32,75833,1550,0,0,New York,19453561,0.389816,0.007968,2.043965
30,18696,267,0,0,New Jersey,8882190,0.210489,0.003006,1.428113
18,5237,239,0,0,Louisiana,4648794,0.112653,0.005141,4.563681
21,6620,89,0,0,Massachusetts,6892503,0.096046,0.001291,1.344411
6,3128,69,0,0,Connecticut,3565287,0.087735,0.001935,2.205882
22,7615,259,0,0,Michigan,9986857,0.076250,0.002593,3.401182
47,5432,225,0,0,Washington,7614893,0.071334,0.002955,4.142121
8,495,9,0,0,District of Columbia,705749,0.070138,0.001275,1.818182
5,2966,69,0,0,Colorado,5758736,0.051504,0.001198,2.326365
13,5994,99,0,0,Illinois,12671821,0.047302,0.000781,1.651652
45,293,13,0,0,Vermont,623989,0.046956,0.002083,4.436860
39,488,8,0,0,Rhode Island,1059361,0.046066,0.000755,1.639344
38,4963,63,0,0,Pennsylvania,12801989,0.038767,0.000492,1.269394
10,3929,111,0,0,Georgia,10617423,0.037005,0.001045,2.825146
28,1114,26,0,0,Nevada,3080156,0.036167,0.000844,2.333932
42,2391,23,0,0,Tennessee,6829174,0.035012,0.000337,0.961941
7,319,10,0,0,Delaware,973764,0.032759,0.001027,3.134796
14,2158,49,0,0,Indiana,6732219,0.032055,0.000728,2.270621
24,937,20,0,0,Mississippi,2976149,0.031484,0.000672,2.134472
9,6741,85,0,0,Florida,21477737,0.031386,0.000396,1.260941
12,515,8,0,0,Idaho,1787065,0.028818,0.000448,1.553398
44,888,5,0,0,Utah,3205958,0.027698,0.000156,0.563063
20,1660,18,0,0,Maryland,6045680,0.027458,0.000298,1.084337
29,357,3,0,0,New Hampshire,1359711,0.026256,0.000221,0.840336
49,1412,25,0,0,Wisconsin,5822434,0.024251,0.000429,1.770538
19,303,5,0,0,Maine,1344212,0.022541,0.000372,1.650165
25,1357,15,0,0,Missouri,6137428,0.022110,0.000244,1.105380
40,1083,22,0,0,South Carolina,5148714,0.021034,0.000427,2.031394
4,8210,173,0,0,California,39512223,0.020778,0.000438,2.107186
0,987,23,0,0,Alabama,4903185,0.020130,0.000469,2.330294
50,109,0,0,0,Wyoming,578759,0.018833,0.000000,0.000000
35,2199,55,0,0,Ohio,11689100,0.018812,0.000471,2.501137
26,198,5,0,0,Montana,1068778,0.018526,0.000468,2.525253
2,1289,24,0,0,Arizona,7278717,0.017709,0.000330,1.861908
3,523,8,0,0,Arkansas,3017804,0.017330,0.000265,1.529637
37,690,18,0,0,Oregon,4217737,0.016359,0.000427,2.608696
1,119,3,0,0,Alaska,731545,0.016267,0.000410,2.521008
34,122,3,0,0,North Dakota,762062,0.016009,0.000394,2.459016
15,497,7,0,0,Iowa,3155070,0.015752,0.000222,1.408451
31,315,4,0,0,New Mexico,2096829,0.015023,0.000191,1.269841
16,434,9,0,0,Kansas,2913314,0.014897,0.000309,2.073733
33,1535,12,0,0,North Carolina,10488084,0.014636,0.000114,0.781759
46,1249,27,0,0,Virginia,8535519,0.014633,0.000316,2.161729
11,204,0,0,0,Hawaii,1415872,0.014408,0.000000,0.000000
36,568,23,0,0,Oklahoma,3956971,0.014354,0.000581,4.049296
17,628,11,0,0,Kentucky,4467673,0.014057,0.000246,1.751592
43,3809,54,0,0,Texas,28995881,0.013136,0.000186,1.417695
41,108,1,0,0,South Dakota,884659,0.012208,0.000113,0.925926
23,629,12,0,0,Minnesota,5639632,0.011153,0.000213,1.907790
48,162,1,0,0,West Virginia,1792147,0.009039,0.000056,0.617284
27,172,3,0,0,Nebraska,1934408,0.008892,0.000155,1.744186

In [19]:
state_with_population.sort_values(by='deaths', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
32,75833,1550,0,0,New York,19453561,0.389816,0.007968,2.043965
18,5237,239,0,0,Louisiana,4648794,0.112653,0.005141,4.563681
30,18696,267,0,0,New Jersey,8882190,0.210489,0.003006,1.428113
47,5432,225,0,0,Washington,7614893,0.071334,0.002955,4.142121
22,7615,259,0,0,Michigan,9986857,0.076250,0.002593,3.401182
45,293,13,0,0,Vermont,623989,0.046956,0.002083,4.436860
6,3128,69,0,0,Connecticut,3565287,0.087735,0.001935,2.205882
21,6620,89,0,0,Massachusetts,6892503,0.096046,0.001291,1.344411
8,495,9,0,0,District of Columbia,705749,0.070138,0.001275,1.818182
5,2966,69,0,0,Colorado,5758736,0.051504,0.001198,2.326365
10,3929,111,0,0,Georgia,10617423,0.037005,0.001045,2.825146
7,319,10,0,0,Delaware,973764,0.032759,0.001027,3.134796
28,1114,26,0,0,Nevada,3080156,0.036167,0.000844,2.333932
13,5994,99,0,0,Illinois,12671821,0.047302,0.000781,1.651652
39,488,8,0,0,Rhode Island,1059361,0.046066,0.000755,1.639344
14,2158,49,0,0,Indiana,6732219,0.032055,0.000728,2.270621
24,937,20,0,0,Mississippi,2976149,0.031484,0.000672,2.134472
36,568,23,0,0,Oklahoma,3956971,0.014354,0.000581,4.049296
38,4963,63,0,0,Pennsylvania,12801989,0.038767,0.000492,1.269394
35,2199,55,0,0,Ohio,11689100,0.018812,0.000471,2.501137
0,987,23,0,0,Alabama,4903185,0.020130,0.000469,2.330294
26,198,5,0,0,Montana,1068778,0.018526,0.000468,2.525253
12,515,8,0,0,Idaho,1787065,0.028818,0.000448,1.553398
4,8210,173,0,0,California,39512223,0.020778,0.000438,2.107186
49,1412,25,0,0,Wisconsin,5822434,0.024251,0.000429,1.770538
40,1083,22,0,0,South Carolina,5148714,0.021034,0.000427,2.031394
37,690,18,0,0,Oregon,4217737,0.016359,0.000427,2.608696
1,119,3,0,0,Alaska,731545,0.016267,0.000410,2.521008
9,6741,85,0,0,Florida,21477737,0.031386,0.000396,1.260941
34,122,3,0,0,North Dakota,762062,0.016009,0.000394,2.459016
19,303,5,0,0,Maine,1344212,0.022541,0.000372,1.650165
42,2391,23,0,0,Tennessee,6829174,0.035012,0.000337,0.961941
2,1289,24,0,0,Arizona,7278717,0.017709,0.000330,1.861908
46,1249,27,0,0,Virginia,8535519,0.014633,0.000316,2.161729
16,434,9,0,0,Kansas,2913314,0.014897,0.000309,2.073733
20,1660,18,0,0,Maryland,6045680,0.027458,0.000298,1.084337
3,523,8,0,0,Arkansas,3017804,0.017330,0.000265,1.529637
17,628,11,0,0,Kentucky,4467673,0.014057,0.000246,1.751592
25,1357,15,0,0,Missouri,6137428,0.022110,0.000244,1.105380
15,497,7,0,0,Iowa,3155070,0.015752,0.000222,1.408451
29,357,3,0,0,New Hampshire,1359711,0.026256,0.000221,0.840336
23,629,12,0,0,Minnesota,5639632,0.011153,0.000213,1.907790
31,315,4,0,0,New Mexico,2096829,0.015023,0.000191,1.269841
43,3809,54,0,0,Texas,28995881,0.013136,0.000186,1.417695
44,888,5,0,0,Utah,3205958,0.027698,0.000156,0.563063
27,172,3,0,0,Nebraska,1934408,0.008892,0.000155,1.744186
33,1535,12,0,0,North Carolina,10488084,0.014636,0.000114,0.781759
41,108,1,0,0,South Dakota,884659,0.012208,0.000113,0.925926
48,162,1,0,0,West Virginia,1792147,0.009039,0.000056,0.617284
11,204,0,0,0,Hawaii,1415872,0.014408,0.000000,0.000000
50,109,0,0,0,Wyoming,578759,0.018833,0.000000,0.000000

In [20]:
state_with_population.describe()

,Confirmed,Deaths,Recovered,Active,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
count,51.000000,51.000000,51.0,51.0,5.100000e+01,51.000000,51.000000,51.000000
mean,3680.000000,75.686275,0.0,0.0,6.436069e+06,0.041844,0.000892,1.928334
std,10794.788457,221.479434,0.0,0.0,7.360660e+06,0.060300,0.001382,0.996244
min,108.000000,0.000000,0.0,0.0,5.787590e+05,0.008892,0.000000,0.000000
25%,395.500000,7.500000,0.0,0.0,1.789606e+06,0.015881,0.000245,1.307126
50%,987.000000,18.000000,0.0,0.0,4.467673e+06,0.022541,0.000427,1.818182
75%,3047.000000,59.000000,0.0,0.0,7.446805e+06,0.037886,0.000813,2.332113
max,75833.000000,1550.000000,0.0,0.0,3.951222e+07,0.389816,0.007968,4.563681