In [1]:
import pandas as pd
import requests
pd.set_option('max_rows', 100)

In [2]:
url = 'https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-29-2020.csv'

### Get daily data from the url

In [3]:
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get(url, headers=header)
df = pd.read_html(r.text, header=[0], index_col=0)[0].iloc[:-1]

#### quick glance at the data

In [4]:
df[df.Country_Region=='US'].sort_values(by='Province_State')

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
NaN,1047.0,Dallas,Alabama,US,2020-03-29 23:08:25,32.326881,-87.108667,2,0,0,0,"Dallas, Alabama, US"
NaN,1055.0,Etowah,Alabama,US,2020-03-29 23:08:25,34.045673,-86.040519,6,0,0,0,"Etowah, Alabama, US"
NaN,1053.0,Escambia,Alabama,US,2020-03-29 23:08:25,31.125679,-87.159187,1,0,0,0,"Escambia, Alabama, US"
NaN,1051.0,Elmore,Alabama,US,2020-03-29 23:08:25,32.597854,-86.144153,13,0,0,0,"Elmore, Alabama, US"
NaN,1009.0,Blount,Alabama,US,2020-03-29 23:08:25,33.982109,-86.567906,5,0,0,0,"Blount, Alabama, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,56031.0,Platte,Wyoming,US,2020-03-29 23:08:25,42.132991,-104.966331,0,0,0,0,"Platte, Wyoming, US"
NaN,56043.0,Washakie,Wyoming,US,2020-03-29 23:08:25,43.904516,-107.680187,1,0,0,0,"Washakie, Wyoming, US"
NaN,56005.0,Campbell,Wyoming,US,2020-03-29 23:08:25,44.248861,-105.547440,1,0,0,0,"Campbell, Wyoming, US"
NaN,56009.0,Converse,Wyoming,US,2020-03-29 23:08:25,42.972723,-105.508185,1,0,0,0,"Converse, Wyoming, US"
NaN,56011.0,Crook,Wyoming,US,2020-03-29 23:08:25,44.588551,-104.569771,0,0,0,0,"Crook, Wyoming, US"

In [5]:
df.describe()

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,3148.000000,3433.000000,3433.000000,3433.000000,3433.000000,3433.000000,3433.000000
mean,30472.462834,36.862569,-82.775425,209.761142,9.881736,43.426158,115.234489
std,15295.724160,10.053753,39.143801,2956.602158,234.890990,1161.951657,2024.815327
min,1001.000000,-42.882100,-170.132000,0.000000,0.000000,0.000000,-6.000000
25%,18180.500000,33.953399,-97.632172,0.000000,0.000000,0.000000,0.000000
50%,29182.000000,38.071225,-89.046796,2.000000,0.000000,0.000000,0.000000
75%,45089.500000,41.729806,-81.727132,10.000000,0.000000,0.000000,0.000000
max,99999.000000,71.706900,178.065000,97689.000000,10779.000000,62570.000000,73880.000000

### Aggregate by state

In [6]:
state_totals = df[df.Country_Region=='US'].groupby(by='Province_State').sum()

In [7]:
state_totals.describe()

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,5.900000e+01,59.000000,59.000000,59.000000,59.000000,59.000000,59.0
mean,1.625887e+06,2050.698623,-4918.486094,2387.898305,41.813559,45.169492,0.0
std,1.995046e+06,1723.851856,4444.368446,7897.064059,129.749291,346.953448,0.0
min,0.000000e+00,-14.271000,-25057.879425,0.000000,0.000000,0.000000,0.0
25%,1.600120e+05,561.685748,-7320.232710,151.500000,2.000000,0.000000,0.0
50%,1.288529e+06,1947.589655,-4708.049596,503.000000,9.000000,0.000000,0.0
75%,2.269284e+06,3302.767521,-1044.429181,1686.500000,30.500000,0.000000,0.0
max,1.225652e+07,8041.803434,145.673900,59648.000000,965.000000,2665.000000,0.0

In [8]:
state_totals.sort_values(by='Confirmed', ascending=False)

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,2235844.0,2637.737383,-4679.399365,59648,965,0,0
New Jersey,714441.0,846.015259,-1567.071444,13386,161,0,0
California,351364.0,2194.949775,-7002.258461,5852,124,0,0
Michigan,2164889.0,3655.617539,-7070.178085,5488,132,0,0
Massachusetts,350196.0,630.994149,-1071.277031,4955,48,0,0
Illinois,1744404.0,4064.049006,-9096.189667,4596,66,0,0
Washington,2068521.0,1842.117670,-4708.049596,4465,198,0,0
Florida,808550.0,1939.030577,-5540.949842,4246,56,0,0
Louisiana,1412096.0,1989.915353,-5876.747946,3540,151,0,0
Pennsylvania,2818489.0,2734.811250,-5200.226295,3432,41,0,0
Texas,12256516.0,8041.803434,-25057.879425,2792,37,0,0
Georgia,2092677.0,5216.556611,-13288.811358,2651,80,0,0
Colorado,515983.0,2491.870366,-6751.119357,2307,47,0,0
Connecticut,72064.0,332.909441,-581.254637,1993,34,0,0
Tennessee,4474025.0,3409.084710,-8180.328684,1720,8,0,0
Ohio,3439744.0,3547.338944,-7289.515905,1653,29,0,0
Indiana,1664464.0,3665.036491,-7932.108297,1513,32,0,0
Maryland,577079.0,936.358097,-1840.211223,1239,10,0,0
North Carolina,3710000.0,3562.420971,-7950.109874,1191,7,0,0
Wisconsin,3965119.0,3196.450332,-6465.454559,1164,18,0,0
Nevada,544774.0,667.351945,-1998.587890,920,15,0,0
Arizona,60208.0,505.138555,-1671.948482,919,17,0,0
Missouri,3348537.0,4460.984726,-10729.940479,915,13,0,0
Virginia,6818111.0,4996.297993,-10442.323661,890,20,0,0
Alabama,71489.0,2203.246784,-5809.578199,825,10,0,0
South Carolina,2072116.0,1562.043718,-3725.236386,774,16,0,0
Mississippi,2302724.0,2689.003578,-7350.949516,759,14,0,0
Utah,1421841.0,1149.410881,-3236.285569,720,2,0,0
Oregon,1477296.0,1601.726424,-4373.169106,548,13,0,0
Minnesota,2356569.0,3963.025129,-8215.492913,503,9,0,0
Kentucky,2534400.0,4514.657262,-10223.986874,438,9,0,0
Oklahoma,3085929.0,2733.647411,-7488.357767,429,16,0,0
Arkansas,380625.0,2618.391704,-6932.548370,426,6,0,0
District of Columbia,11001.0,38.904178,-77.016560,342,5,0,0
Iowa,1890801.0,4160.961092,-9253.086423,336,4,0,0
Kansas,2111025.0,4040.964784,-10298.877911,330,7,0,0
Rhode Island,220025.0,208.275711,-357.320525,294,3,0,0
Idaho,705936.0,1947.589655,-5036.245496,281,5,0,0
Maine,368256.0,715.003014,-1112.380298,253,3,0,0
New Mexico,1155995.0,1172.481604,-3601.107483,237,2,0,0
Vermont,700196.0,618.232941,-1017.581330,235,12,0,0
Delaware,30009.0,117.327830,-226.599712,232,6,0,0
New Hampshire,330100.0,434.789729,-715.776567,214,2,0,0
Montana,1683136.0,2630.582703,-6143.222113,154,1,0,0
Hawaii,75025.0,105.141415,-786.616182,149,0,0,0
Puerto Rico,0.0,18.220800,-66.590100,127,3,0,0
West Virginia,2973025.0,2134.783954,-4433.959998,113,0,0,0
Nebraska,2891649.0,3842.926930,-9210.628137,108,2,0,0
Grand Princess,99999.0,0.000000,0.000000,103,3,0,0
Alaska,62340.0,1747.579877,-4229.319334,102,2,0,0
North Dakota,2016809.0,2511.855857,-5313.217852,98,1,0,0
South Dakota,3040485.0,2921.997865,-6554.501988,90,1,0,0
Wyoming,1288529.0,990.998367,-2464.524571,86,0,0,0
Guam,66000.0,13.444300,144.793700,56,1,0,0
Diamond Princess,88888.0,0.000000,0.000000,49,0,0,0
Virgin Islands,78000.0,18.335800,-64.896300,0,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,2665,0
American Samoa,60000.0,-14.271000,-170.132000,0,0,0,0
Northern Mariana Islands,69000.0,15.097900,145.673900,0,0,0,0

In [9]:
state_totals.sort_values(by='Confirmed', ascending=False)

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,2235844.0,2637.737383,-4679.399365,59648,965,0,0
New Jersey,714441.0,846.015259,-1567.071444,13386,161,0,0
California,351364.0,2194.949775,-7002.258461,5852,124,0,0
Michigan,2164889.0,3655.617539,-7070.178085,5488,132,0,0
Massachusetts,350196.0,630.994149,-1071.277031,4955,48,0,0
Illinois,1744404.0,4064.049006,-9096.189667,4596,66,0,0
Washington,2068521.0,1842.117670,-4708.049596,4465,198,0,0
Florida,808550.0,1939.030577,-5540.949842,4246,56,0,0
Louisiana,1412096.0,1989.915353,-5876.747946,3540,151,0,0
Pennsylvania,2818489.0,2734.811250,-5200.226295,3432,41,0,0
Texas,12256516.0,8041.803434,-25057.879425,2792,37,0,0
Georgia,2092677.0,5216.556611,-13288.811358,2651,80,0,0
Colorado,515983.0,2491.870366,-6751.119357,2307,47,0,0
Connecticut,72064.0,332.909441,-581.254637,1993,34,0,0
Tennessee,4474025.0,3409.084710,-8180.328684,1720,8,0,0
Ohio,3439744.0,3547.338944,-7289.515905,1653,29,0,0
Indiana,1664464.0,3665.036491,-7932.108297,1513,32,0,0
Maryland,577079.0,936.358097,-1840.211223,1239,10,0,0
North Carolina,3710000.0,3562.420971,-7950.109874,1191,7,0,0
Wisconsin,3965119.0,3196.450332,-6465.454559,1164,18,0,0
Nevada,544774.0,667.351945,-1998.587890,920,15,0,0
Arizona,60208.0,505.138555,-1671.948482,919,17,0,0
Missouri,3348537.0,4460.984726,-10729.940479,915,13,0,0
Virginia,6818111.0,4996.297993,-10442.323661,890,20,0,0
Alabama,71489.0,2203.246784,-5809.578199,825,10,0,0
South Carolina,2072116.0,1562.043718,-3725.236386,774,16,0,0
Mississippi,2302724.0,2689.003578,-7350.949516,759,14,0,0
Utah,1421841.0,1149.410881,-3236.285569,720,2,0,0
Oregon,1477296.0,1601.726424,-4373.169106,548,13,0,0
Minnesota,2356569.0,3963.025129,-8215.492913,503,9,0,0
Kentucky,2534400.0,4514.657262,-10223.986874,438,9,0,0
Oklahoma,3085929.0,2733.647411,-7488.357767,429,16,0,0
Arkansas,380625.0,2618.391704,-6932.548370,426,6,0,0
District of Columbia,11001.0,38.904178,-77.016560,342,5,0,0
Iowa,1890801.0,4160.961092,-9253.086423,336,4,0,0
Kansas,2111025.0,4040.964784,-10298.877911,330,7,0,0
Rhode Island,220025.0,208.275711,-357.320525,294,3,0,0
Idaho,705936.0,1947.589655,-5036.245496,281,5,0,0
Maine,368256.0,715.003014,-1112.380298,253,3,0,0
New Mexico,1155995.0,1172.481604,-3601.107483,237,2,0,0
Vermont,700196.0,618.232941,-1017.581330,235,12,0,0
Delaware,30009.0,117.327830,-226.599712,232,6,0,0
New Hampshire,330100.0,434.789729,-715.776567,214,2,0,0
Montana,1683136.0,2630.582703,-6143.222113,154,1,0,0
Hawaii,75025.0,105.141415,-786.616182,149,0,0,0
Puerto Rico,0.0,18.220800,-66.590100,127,3,0,0
West Virginia,2973025.0,2134.783954,-4433.959998,113,0,0,0
Nebraska,2891649.0,3842.926930,-9210.628137,108,2,0,0
Grand Princess,99999.0,0.000000,0.000000,103,3,0,0
Alaska,62340.0,1747.579877,-4229.319334,102,2,0,0
North Dakota,2016809.0,2511.855857,-5313.217852,98,1,0,0
South Dakota,3040485.0,2921.997865,-6554.501988,90,1,0,0
Wyoming,1288529.0,990.998367,-2464.524571,86,0,0,0
Guam,66000.0,13.444300,144.793700,56,1,0,0
Diamond Princess,88888.0,0.000000,0.000000,49,0,0,0
Virgin Islands,78000.0,18.335800,-64.896300,0,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,2665,0
American Samoa,60000.0,-14.271000,-170.132000,0,0,0,0
Northern Mariana Islands,69000.0,15.097900,145.673900,0,0,0,0

In [10]:
df[df.Country_Region=='US'].groupby(by='Province_State').sum().sort_values(by='Deaths', ascending=False)

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,2235844.0,2637.737383,-4679.399365,59648,965,0,0
Washington,2068521.0,1842.117670,-4708.049596,4465,198,0,0
New Jersey,714441.0,846.015259,-1567.071444,13386,161,0,0
Louisiana,1412096.0,1989.915353,-5876.747946,3540,151,0,0
Michigan,2164889.0,3655.617539,-7070.178085,5488,132,0,0
California,351364.0,2194.949775,-7002.258461,5852,124,0,0
Georgia,2092677.0,5216.556611,-13288.811358,2651,80,0,0
Illinois,1744404.0,4064.049006,-9096.189667,4596,66,0,0
Florida,808550.0,1939.030577,-5540.949842,4246,56,0,0
Massachusetts,350196.0,630.994149,-1071.277031,4955,48,0,0
Colorado,515983.0,2491.870366,-6751.119357,2307,47,0,0
Pennsylvania,2818489.0,2734.811250,-5200.226295,3432,41,0,0
Texas,12256516.0,8041.803434,-25057.879425,2792,37,0,0
Connecticut,72064.0,332.909441,-581.254637,1993,34,0,0
Indiana,1664464.0,3665.036491,-7932.108297,1513,32,0,0
Ohio,3439744.0,3547.338944,-7289.515905,1653,29,0,0
Virginia,6818111.0,4996.297993,-10442.323661,890,20,0,0
Wisconsin,3965119.0,3196.450332,-6465.454559,1164,18,0,0
Arizona,60208.0,505.138555,-1671.948482,919,17,0,0
South Carolina,2072116.0,1562.043718,-3725.236386,774,16,0,0
Oklahoma,3085929.0,2733.647411,-7488.357767,429,16,0,0
Nevada,544774.0,667.351945,-1998.587890,920,15,0,0
Mississippi,2302724.0,2689.003578,-7350.949516,759,14,0,0
Oregon,1477296.0,1601.726424,-4373.169106,548,13,0,0
Missouri,3348537.0,4460.984726,-10729.940479,915,13,0,0
Vermont,700196.0,618.232941,-1017.581330,235,12,0,0
Alabama,71489.0,2203.246784,-5809.578199,825,10,0,0
Maryland,577079.0,936.358097,-1840.211223,1239,10,0,0
Minnesota,2356569.0,3963.025129,-8215.492913,503,9,0,0
Kentucky,2534400.0,4514.657262,-10223.986874,438,9,0,0
Tennessee,4474025.0,3409.084710,-8180.328684,1720,8,0,0
Kansas,2111025.0,4040.964784,-10298.877911,330,7,0,0
North Carolina,3710000.0,3562.420971,-7950.109874,1191,7,0,0
Delaware,30009.0,117.327830,-226.599712,232,6,0,0
Arkansas,380625.0,2618.391704,-6932.548370,426,6,0,0
Idaho,705936.0,1947.589655,-5036.245496,281,5,0,0
District of Columbia,11001.0,38.904178,-77.016560,342,5,0,0
Iowa,1890801.0,4160.961092,-9253.086423,336,4,0,0
Maine,368256.0,715.003014,-1112.380298,253,3,0,0
Puerto Rico,0.0,18.220800,-66.590100,127,3,0,0
Rhode Island,220025.0,208.275711,-357.320525,294,3,0,0
Grand Princess,99999.0,0.000000,0.000000,103,3,0,0
New Hampshire,330100.0,434.789729,-715.776567,214,2,0,0
New Mexico,1155995.0,1172.481604,-3601.107483,237,2,0,0
Nebraska,2891649.0,3842.926930,-9210.628137,108,2,0,0
Utah,1421841.0,1149.410881,-3236.285569,720,2,0,0
Alaska,62340.0,1747.579877,-4229.319334,102,2,0,0
South Dakota,3040485.0,2921.997865,-6554.501988,90,1,0,0
Guam,66000.0,13.444300,144.793700,56,1,0,0
North Dakota,2016809.0,2511.855857,-5313.217852,98,1,0,0
Montana,1683136.0,2630.582703,-6143.222113,154,1,0,0
Recovered,0.0,0.000000,0.000000,0,0,2665,0
Hawaii,75025.0,105.141415,-786.616182,149,0,0,0
Northern Mariana Islands,69000.0,15.097900,145.673900,0,0,0,0
Diamond Princess,88888.0,0.000000,0.000000,49,0,0,0
Virgin Islands,78000.0,18.335800,-64.896300,0,0,0,0
West Virginia,2973025.0,2134.783954,-4433.959998,113,0,0,0
American Samoa,60000.0,-14.271000,-170.132000,0,0,0,0
Wyoming,1288529.0,990.998367,-2464.524571,86,0,0,0

In [11]:
df[df.Province_State=='New Jersey'].sort_values(by='Confirmed', ascending=False)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
NaN,NaN,Unassigned,New Jersey,US,2020-03-29 23:08:25,0.000000,0.000000,3020,56,0,0,"Unassigned, New Jersey, US"
NaN,34003.0,Bergen,New Jersey,US,2020-03-29 23:08:25,40.960109,-74.071643,2169,23,0,0,"Bergen, New Jersey, US"
NaN,34013.0,Essex,New Jersey,US,2020-03-29 23:08:25,40.786813,-74.246580,1227,13,0,0,"Essex, New Jersey, US"
NaN,34017.0,Hudson,New Jersey,US,2020-03-29 23:08:25,40.737662,-74.075157,974,6,0,0,"Hudson, New Jersey, US"
NaN,34023.0,Middlesex,New Jersey,US,2020-03-29 23:08:25,40.436299,-74.414270,938,12,0,0,"Middlesex, New Jersey, US"
NaN,34039.0,Union,New Jersey,US,2020-03-29 23:08:25,40.658354,-74.306801,896,7,0,0,"Union, New Jersey, US"
NaN,34025.0,Monmouth,New Jersey,US,2020-03-29 23:08:25,40.265497,-74.222407,870,8,0,0,"Monmouth, New Jersey, US"
NaN,34031.0,Passaic,New Jersey,US,2020-03-29 23:08:25,41.032386,-74.299541,831,10,0,0,"Passaic, New Jersey, US"
NaN,34029.0,Ocean,New Jersey,US,2020-03-29 23:08:25,39.889545,-74.280893,759,6,0,0,"Ocean, New Jersey, US"
NaN,34027.0,Morris,New Jersey,US,2020-03-29 23:08:25,40.860953,-74.545537,566,8,0,0,"Morris, New Jersey, US"
NaN,34035.0,Somerset,New Jersey,US,2020-03-29 23:08:25,40.564657,-74.616830,295,6,0,0,"Somerset, New Jersey, US"
NaN,34021.0,Mercer,New Jersey,US,2020-03-29 23:08:25,40.280470,-74.704796,202,0,0,0,"Mercer, New Jersey, US"
NaN,34007.0,Camden,New Jersey,US,2020-03-29 23:08:25,39.803438,-74.963888,163,1,0,0,"Camden, New Jersey, US"
NaN,34005.0,Burlington,New Jersey,US,2020-03-29 23:08:25,39.876811,-74.669278,142,2,0,0,"Burlington, New Jersey, US"
NaN,34037.0,Sussex,New Jersey,US,2020-03-29 23:08:25,41.138916,-74.691182,93,1,0,0,"Sussex, New Jersey, US"
NaN,34015.0,Gloucester,New Jersey,US,2020-03-29 23:08:25,39.715811,-75.139955,72,1,0,0,"Gloucester, New Jersey, US"
NaN,34019.0,Hunterdon,New Jersey,US,2020-03-29 23:08:25,40.563352,-74.912842,66,0,0,0,"Hunterdon, New Jersey, US"
NaN,34041.0,Warren,New Jersey,US,2020-03-29 23:08:25,40.859518,-74.995565,56,1,0,0,"Warren, New Jersey, US"
NaN,34001.0,Atlantic,New Jersey,US,2020-03-29 23:08:25,39.475387,-74.658485,24,0,0,0,"Atlantic, New Jersey, US"
NaN,34011.0,Cumberland,New Jersey,US,2020-03-29 23:08:25,39.371994,-75.107126,11,0,0,0,"Cumberland, New Jersey, US"
NaN,34009.0,Cape May,New Jersey,US,2020-03-29 23:08:25,39.150088,-74.801702,9,0,0,0,"Cape May, New Jersey, US"
NaN,34033.0,Salem,New Jersey,US,2020-03-29 23:08:25,39.587197,-75.346966,3,0,0,0,"Salem, New Jersey, US"

In [12]:
df[df.Province_State=='New York'].sort_values(by='Confirmed')

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
NaN,36123.0,Yates,New York,US,2020-03-29 23:08:25,42.635055,-77.103699,0,0,0,0,"Yates, New York, US"
NaN,36005.0,Bronx,New York,US,2020-03-29 23:08:25,40.852093,-73.862828,0,0,0,0,"Bronx, New York, US"
NaN,36081.0,Queens,New York,US,2020-03-29 23:08:25,40.710881,-73.816847,0,0,0,0,"Queens, New York, US"
NaN,36099.0,Seneca,New York,US,2020-03-29 23:08:25,42.780810,-76.824971,0,0,0,0,"Seneca, New York, US"
NaN,NaN,Unassigned,New York,US,2020-03-29 23:08:25,0.000000,0.000000,0,159,0,0,"Unassigned, New York, US"
NaN,36049.0,Lewis,New York,US,2020-03-29 23:08:25,43.784416,-75.449040,0,0,0,0,"Lewis, New York, US"
NaN,36047.0,Kings,New York,US,2020-03-29 23:08:25,40.636182,-73.949356,0,0,0,0,"Kings, New York, US"
NaN,36085.0,Richmond,New York,US,2020-03-29 23:08:25,40.585822,-74.148086,0,0,0,0,"Richmond, New York, US"
NaN,36097.0,Schuyler,New York,US,2020-03-29 23:08:25,42.391840,-76.877330,1,0,0,0,"Schuyler, New York, US"
NaN,36035.0,Fulton,New York,US,2020-03-29 23:08:25,43.113639,-74.417988,1,0,0,0,"Fulton, New York, US"
NaN,36011.0,Cayuga,New York,US,2020-03-29 23:08:25,42.912617,-76.557316,2,0,0,0,"Cayuga, New York, US"
NaN,36041.0,Hamilton,New York,US,2020-03-29 23:08:25,43.661466,-74.497220,2,0,0,0,"Hamilton, New York, US"
NaN,36073.0,Orleans,New York,US,2020-03-29 23:08:25,43.251698,-78.232007,3,0,0,0,"Orleans, New York, US"
NaN,36009.0,Cattaraugus,New York,US,2020-03-29 23:08:25,42.247782,-78.679231,4,0,0,0,"Cattaraugus, New York, US"
NaN,36031.0,Essex,New York,US,2020-03-29 23:08:25,44.116308,-73.772978,5,0,0,0,"Essex, New York, US"
NaN,36095.0,Schoharie,New York,US,2020-03-29 23:08:25,42.588317,-74.443390,5,0,0,0,"Schoharie, New York, US"
NaN,36033.0,Franklin,New York,US,2020-03-29 23:08:25,44.590409,-74.299260,6,0,0,0,"Franklin, New York, US"
NaN,36003.0,Allegany,New York,US,2020-03-29 23:08:25,42.257484,-78.027505,6,0,0,0,"Allegany, New York, US"
NaN,36107.0,Tioga,New York,US,2020-03-29 23:08:25,42.168528,-76.308358,6,0,0,0,"Tioga, New York, US"
NaN,36057.0,Montgomery,New York,US,2020-03-29 23:08:25,42.901235,-74.440116,6,0,0,0,"Montgomery, New York, US"
NaN,36039.0,Greene,New York,US,2020-03-29 23:08:25,42.275797,-74.123849,7,0,0,0,"Greene, New York, US"
NaN,36045.0,Jefferson,New York,US,2020-03-29 23:08:25,44.042010,-75.946535,7,0,0,0,"Jefferson, New York, US"
NaN,36013.0,Chautauqua,New York,US,2020-03-29 23:08:25,42.227692,-79.366918,7,0,0,0,"Chautauqua, New York, US"
NaN,36025.0,Delaware,New York,US,2020-03-29 23:08:25,42.198376,-74.967093,8,0,0,0,"Delaware, New York, US"
NaN,36023.0,Cortland,New York,US,2020-03-29 23:08:25,42.595092,-76.070489,8,0,0,0,"Cortland, New York, US"
NaN,36121.0,Wyoming,New York,US,2020-03-29 23:08:25,42.701451,-78.221996,8,1,0,0,"Wyoming, New York, US"
NaN,36037.0,Genesee,New York,US,2020-03-29 23:08:25,43.002260,-78.191352,9,0,0,0,"Genesee, New York, US"
NaN,36115.0,Washington,New York,US,2020-03-29 23:08:25,43.311538,-73.430434,9,0,0,0,"Washington, New York, US"
NaN,36077.0,Otsego,New York,US,2020-03-29 23:08:25,42.634926,-75.031514,10,1,0,0,"Otsego, New York, US"
NaN,36075.0,Oswego,New York,US,2020-03-29 23:08:25,43.427789,-76.146352,10,0,0,0,"Oswego, New York, US"
NaN,36043.0,Herkimer,New York,US,2020-03-29 23:08:25,43.420342,-74.961453,10,2,0,0,"Herkimer, New York, US"
NaN,36051.0,Livingston,New York,US,2020-03-29 23:08:25,42.725963,-77.779662,10,0,0,0,"Livingston, New York, US"
NaN,36089.0,St. Lawrence,New York,US,2020-03-29 23:08:25,44.497618,-75.065500,12,0,0,0,"St. Lawrence, New York, US"
NaN,36117.0,Wayne,New York,US,2020-03-29 23:08:25,43.154944,-77.029765,12,0,0,0,"Wayne, New York, US"
NaN,36019.0,Clinton,New York,US,2020-03-29 23:08:25,44.745309,-73.678754,13,0,0,0,"Clinton, New York, US"
NaN,36015.0,Chemung,New York,US,2020-03-29 23:08:25,42.138911,-76.763880,15,0,0,0,"Chemung, New York, US"
NaN,36017.0,Chenango,New York,US,2020-03-29 23:08:25,42.494300,-75.608876,15,0,0,0,"Chenango, New York, US"
NaN,36101.0,Steuben,New York,US,2020-03-29 23:08:25,42.268914,-77.382992,17,0,0,0,"Steuben, New York, US"
NaN,36069.0,Ontario,New York,US,2020-03-29 23:08:25,42.851457,-77.308744,18,0,0,0,"Ontario, New York, US"
NaN,36113.0,Warren,New York,US,2020-03-29 23:08:25,43.561730,-73.843370,18,0,0,0,"Warren, New York, US"
NaN,36065.0,Oneida,New York,US,2020-03-29 23:08:25,43.243754,-75.437104,26,0,0,0,"Oneida, New York, US"
NaN,36053.0,Madison,New York,US,2020-03-29 23:08:25,42.916539,-75.672666,29,1,0,0,"Madison, New York, US"
NaN,36007.0,Broome,New York,US,2020-03-29 23:08:25,42.159032,-75.813261,29,3,0,0,"Broome, New York, US"
NaN,36021.0,Columbia,New York,US,2020-03-29 23:08:25,42.248193,-73.630891,30,1,0,0,"Columbia, New York, US"
NaN,36063.0,Niagara,New York,US,2020-03-29 23:08:25,43.198980,-78.747774,38,0,0,0,"Niagara, New York, US"
NaN,36083.0,Rensselaer,New York,US,2020-03-29 23:08:25,42.713481,-73.510899,51,0,0,0,"Rensselaer, New York, US"
NaN,36109.0,Tompkins,New York,US,2020-03-29 23:08:25,42.449458,-76.472298,56,0,0,0,"Tompkins, New York, US"
NaN,36093.0,Schenectady,New York,US,2020-03-29 23:08:25,42.816688,-74.052783,76,1,0,0,"Schenectady, New York, US"
NaN,36105.0,Sullivan,New York,US,2020-03-29 23:08:25,41.715795,-74.763946,88,0,0,0,"Sullivan, New York, US"
NaN,36091.0,Saratoga,New York,US,2020-03-29 23:08:25,43.109042,-73.866539,102,0,0,0,"Saratoga, New York, US"
NaN,36079.0,Putnam,New York,US,2020-03-29 23:08:25,41.426301,-73.749655,144,0,0,0,"Putnam, New York, US"
NaN,36111.0,Ulster,New York,US,2020-03-29 23:08:25,41.890279,-74.262521,146,0,0,0,"Ulster, New York, US"
NaN,36067.0,Onondaga,New York,US,2020-03-29 23:08:25,43.004919,-76.199712,194,1,0,0,"Onondaga, New York, US"
NaN,36001.0,Albany,New York,US,2020-03-29 23:08:25,42.600603,-73.977239,205,1,0,0,"Albany, New York, US"
NaN,36055.0,Monroe,New York,US,2020-03-29 23:08:25,43.146389,-77.693229,219,5,0,0,"Monroe, New York, US"
NaN,36027.0,Dutchess,New York,US,2020-03-29 23:08:25,41.764861,-73.743567,320,2,0,0,"Dutchess, New York, US"
NaN,36029.0,Erie,New York,US,2020-03-29 23:08:25,42.762490,-78.730637,414,7,0,0,"Erie, New York, US"
NaN,36071.0,Orange,New York,US,2020-03-29 23:08:25,41.403375,-74.302408,1247,5,0,0,"Orange, New York, US"
NaN,36087.0,Rockland,New York,US,2020-03-29 23:08:25,41.150279,-74.025605,2209,8,0,0,"Rockland, New York, US"
NaN,36103.0,Suffolk,New York,US,2020-03-29 23:08:25,40.883201,-72.801217,5023,40,0,0,"Suffolk, New York, US"
NaN,36059.0,Nassau,New York,US,2020-03-29 23:08:25,40.740665,-73.589419,6445,39,0,0,"Nassau, New York, US"
NaN,36119.0,Westchester,New York,US,2020-03-29 23:08:25,41.162784,-73.757417,8519,10,0,0,"Westchester, New York, US"
NaN,36061.0,New York City,New York,US,2020-03-29 23:08:25,40.767273,-73.971526,33768,678,0,0,"New York City, New York, US"

In [13]:
df[df.Province_State=='New York'].sort_values(by='Confirmed')

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
NaN,36123.0,Yates,New York,US,2020-03-29 23:08:25,42.635055,-77.103699,0,0,0,0,"Yates, New York, US"
NaN,36005.0,Bronx,New York,US,2020-03-29 23:08:25,40.852093,-73.862828,0,0,0,0,"Bronx, New York, US"
NaN,36081.0,Queens,New York,US,2020-03-29 23:08:25,40.710881,-73.816847,0,0,0,0,"Queens, New York, US"
NaN,36099.0,Seneca,New York,US,2020-03-29 23:08:25,42.780810,-76.824971,0,0,0,0,"Seneca, New York, US"
NaN,NaN,Unassigned,New York,US,2020-03-29 23:08:25,0.000000,0.000000,0,159,0,0,"Unassigned, New York, US"
NaN,36049.0,Lewis,New York,US,2020-03-29 23:08:25,43.784416,-75.449040,0,0,0,0,"Lewis, New York, US"
NaN,36047.0,Kings,New York,US,2020-03-29 23:08:25,40.636182,-73.949356,0,0,0,0,"Kings, New York, US"
NaN,36085.0,Richmond,New York,US,2020-03-29 23:08:25,40.585822,-74.148086,0,0,0,0,"Richmond, New York, US"
NaN,36097.0,Schuyler,New York,US,2020-03-29 23:08:25,42.391840,-76.877330,1,0,0,0,"Schuyler, New York, US"
NaN,36035.0,Fulton,New York,US,2020-03-29 23:08:25,43.113639,-74.417988,1,0,0,0,"Fulton, New York, US"
NaN,36011.0,Cayuga,New York,US,2020-03-29 23:08:25,42.912617,-76.557316,2,0,0,0,"Cayuga, New York, US"
NaN,36041.0,Hamilton,New York,US,2020-03-29 23:08:25,43.661466,-74.497220,2,0,0,0,"Hamilton, New York, US"
NaN,36073.0,Orleans,New York,US,2020-03-29 23:08:25,43.251698,-78.232007,3,0,0,0,"Orleans, New York, US"
NaN,36009.0,Cattaraugus,New York,US,2020-03-29 23:08:25,42.247782,-78.679231,4,0,0,0,"Cattaraugus, New York, US"
NaN,36031.0,Essex,New York,US,2020-03-29 23:08:25,44.116308,-73.772978,5,0,0,0,"Essex, New York, US"
NaN,36095.0,Schoharie,New York,US,2020-03-29 23:08:25,42.588317,-74.443390,5,0,0,0,"Schoharie, New York, US"
NaN,36033.0,Franklin,New York,US,2020-03-29 23:08:25,44.590409,-74.299260,6,0,0,0,"Franklin, New York, US"
NaN,36003.0,Allegany,New York,US,2020-03-29 23:08:25,42.257484,-78.027505,6,0,0,0,"Allegany, New York, US"
NaN,36107.0,Tioga,New York,US,2020-03-29 23:08:25,42.168528,-76.308358,6,0,0,0,"Tioga, New York, US"
NaN,36057.0,Montgomery,New York,US,2020-03-29 23:08:25,42.901235,-74.440116,6,0,0,0,"Montgomery, New York, US"
NaN,36039.0,Greene,New York,US,2020-03-29 23:08:25,42.275797,-74.123849,7,0,0,0,"Greene, New York, US"
NaN,36045.0,Jefferson,New York,US,2020-03-29 23:08:25,44.042010,-75.946535,7,0,0,0,"Jefferson, New York, US"
NaN,36013.0,Chautauqua,New York,US,2020-03-29 23:08:25,42.227692,-79.366918,7,0,0,0,"Chautauqua, New York, US"
NaN,36025.0,Delaware,New York,US,2020-03-29 23:08:25,42.198376,-74.967093,8,0,0,0,"Delaware, New York, US"
NaN,36023.0,Cortland,New York,US,2020-03-29 23:08:25,42.595092,-76.070489,8,0,0,0,"Cortland, New York, US"
NaN,36121.0,Wyoming,New York,US,2020-03-29 23:08:25,42.701451,-78.221996,8,1,0,0,"Wyoming, New York, US"
NaN,36037.0,Genesee,New York,US,2020-03-29 23:08:25,43.002260,-78.191352,9,0,0,0,"Genesee, New York, US"
NaN,36115.0,Washington,New York,US,2020-03-29 23:08:25,43.311538,-73.430434,9,0,0,0,"Washington, New York, US"
NaN,36077.0,Otsego,New York,US,2020-03-29 23:08:25,42.634926,-75.031514,10,1,0,0,"Otsego, New York, US"
NaN,36075.0,Oswego,New York,US,2020-03-29 23:08:25,43.427789,-76.146352,10,0,0,0,"Oswego, New York, US"
NaN,36043.0,Herkimer,New York,US,2020-03-29 23:08:25,43.420342,-74.961453,10,2,0,0,"Herkimer, New York, US"
NaN,36051.0,Livingston,New York,US,2020-03-29 23:08:25,42.725963,-77.779662,10,0,0,0,"Livingston, New York, US"
NaN,36089.0,St. Lawrence,New York,US,2020-03-29 23:08:25,44.497618,-75.065500,12,0,0,0,"St. Lawrence, New York, US"
NaN,36117.0,Wayne,New York,US,2020-03-29 23:08:25,43.154944,-77.029765,12,0,0,0,"Wayne, New York, US"
NaN,36019.0,Clinton,New York,US,2020-03-29 23:08:25,44.745309,-73.678754,13,0,0,0,"Clinton, New York, US"
NaN,36015.0,Chemung,New York,US,2020-03-29 23:08:25,42.138911,-76.763880,15,0,0,0,"Chemung, New York, US"
NaN,36017.0,Chenango,New York,US,2020-03-29 23:08:25,42.494300,-75.608876,15,0,0,0,"Chenango, New York, US"
NaN,36101.0,Steuben,New York,US,2020-03-29 23:08:25,42.268914,-77.382992,17,0,0,0,"Steuben, New York, US"
NaN,36069.0,Ontario,New York,US,2020-03-29 23:08:25,42.851457,-77.308744,18,0,0,0,"Ontario, New York, US"
NaN,36113.0,Warren,New York,US,2020-03-29 23:08:25,43.561730,-73.843370,18,0,0,0,"Warren, New York, US"
NaN,36065.0,Oneida,New York,US,2020-03-29 23:08:25,43.243754,-75.437104,26,0,0,0,"Oneida, New York, US"
NaN,36053.0,Madison,New York,US,2020-03-29 23:08:25,42.916539,-75.672666,29,1,0,0,"Madison, New York, US"
NaN,36007.0,Broome,New York,US,2020-03-29 23:08:25,42.159032,-75.813261,29,3,0,0,"Broome, New York, US"
NaN,36021.0,Columbia,New York,US,2020-03-29 23:08:25,42.248193,-73.630891,30,1,0,0,"Columbia, New York, US"
NaN,36063.0,Niagara,New York,US,2020-03-29 23:08:25,43.198980,-78.747774,38,0,0,0,"Niagara, New York, US"
NaN,36083.0,Rensselaer,New York,US,2020-03-29 23:08:25,42.713481,-73.510899,51,0,0,0,"Rensselaer, New York, US"
NaN,36109.0,Tompkins,New York,US,2020-03-29 23:08:25,42.449458,-76.472298,56,0,0,0,"Tompkins, New York, US"
NaN,36093.0,Schenectady,New York,US,2020-03-29 23:08:25,42.816688,-74.052783,76,1,0,0,"Schenectady, New York, US"
NaN,36105.0,Sullivan,New York,US,2020-03-29 23:08:25,41.715795,-74.763946,88,0,0,0,"Sullivan, New York, US"
NaN,36091.0,Saratoga,New York,US,2020-03-29 23:08:25,43.109042,-73.866539,102,0,0,0,"Saratoga, New York, US"
NaN,36079.0,Putnam,New York,US,2020-03-29 23:08:25,41.426301,-73.749655,144,0,0,0,"Putnam, New York, US"
NaN,36111.0,Ulster,New York,US,2020-03-29 23:08:25,41.890279,-74.262521,146,0,0,0,"Ulster, New York, US"
NaN,36067.0,Onondaga,New York,US,2020-03-29 23:08:25,43.004919,-76.199712,194,1,0,0,"Onondaga, New York, US"
NaN,36001.0,Albany,New York,US,2020-03-29 23:08:25,42.600603,-73.977239,205,1,0,0,"Albany, New York, US"
NaN,36055.0,Monroe,New York,US,2020-03-29 23:08:25,43.146389,-77.693229,219,5,0,0,"Monroe, New York, US"
NaN,36027.0,Dutchess,New York,US,2020-03-29 23:08:25,41.764861,-73.743567,320,2,0,0,"Dutchess, New York, US"
NaN,36029.0,Erie,New York,US,2020-03-29 23:08:25,42.762490,-78.730637,414,7,0,0,"Erie, New York, US"
NaN,36071.0,Orange,New York,US,2020-03-29 23:08:25,41.403375,-74.302408,1247,5,0,0,"Orange, New York, US"
NaN,36087.0,Rockland,New York,US,2020-03-29 23:08:25,41.150279,-74.025605,2209,8,0,0,"Rockland, New York, US"
NaN,36103.0,Suffolk,New York,US,2020-03-29 23:08:25,40.883201,-72.801217,5023,40,0,0,"Suffolk, New York, US"
NaN,36059.0,Nassau,New York,US,2020-03-29 23:08:25,40.740665,-73.589419,6445,39,0,0,"Nassau, New York, US"
NaN,36119.0,Westchester,New York,US,2020-03-29 23:08:25,41.162784,-73.757417,8519,10,0,0,"Westchester, New York, US"
NaN,36061.0,New York City,New York,US,2020-03-29 23:08:25,40.767273,-73.971526,33768,678,0,0,"New York City, New York, US"

In [14]:
population = pd.read_csv('data/SCPRC-EST2019-18+POP-RES.csv')
population.sort_values(by='POPESTIMATE2019', ascending=False).head(10)

,SUMLEV,REGION,DIVISION,STATE,NAME,POPESTIMATE2019,POPEST18PLUS2019,PCNT_POPEST18PLUS
0,10,0,0,0,United States,328239523,255200373,77.7
5,40,4,9,6,California,39512223,30617582,77.5
44,40,3,7,48,Texas,28995881,21596071,74.5
10,40,3,5,12,Florida,21477737,17247808,80.3
33,40,1,2,36,New York,19453561,15425262,79.3
39,40,1,2,42,Pennsylvania,12801989,10167376,79.4
14,40,2,3,17,Illinois,12671821,9853946,77.8
36,40,2,3,39,Ohio,11689100,9111081,77.9
11,40,3,5,13,Georgia,10617423,8113542,76.4
34,40,3,5,37,North Carolina,10488084,8187369,78.1

In [15]:
geog = pd.read_csv('data/us_geography.csv')
geog.head(10)

,State,tot_sq_mi,tot_sq_km,land_sq_mi,land_sq_km,water_sq_mi,water_sq_km,inland_sq_mi,inland_sq_km,coast_sq_mi,coast_sq_km,gl_sq_mi,gl_sq_km,terr_sq_mi,terr_sq_km,latitude,longitude
0,United States,"3,796,742","9,833,517","3,531,905","9,147,593","264,837","685,924","85,647","221,824","42,337","109,652","60,094","155,643","76,759","198,806",NaN,NaN
1,Alabama,"52,420","135,767","50,645","131,171","1,775","4,597","1,058","2,740",517,"1,340",â€”,â€”,199,516,32.739632,-86.843459
2,Alaska,"665,384","1,723,337","570,641","1,477,953","94,743","245,383","19,304","49,997","26,119","67,647",â€”,â€”,"49,320","127,739",63.346191,-152.837068
3,Arizona,"113,990","295,234","113,594","294,207",396,"1,026",396,"1,026",â€”,â€”,â€”,â€”,â€”,â€”,34.209964,-111.602401
4,Arkansas,"53,179","137,732","52,035","134,771","1,143","2,961","1,143","2,961",â€”,â€”,â€”,â€”,â€”,â€”,34.895526,-92.444626
5,California,"163,695","423,967","155,779","403,466","7,916","20,501","2,833","7,339",245,634,â€”,â€”,"4,837","12,528",37.148573,-119.540651
6,Colorado,"104,094","269,601","103,642","268,431",452,"1,170",452,"1,170",â€”,â€”,â€”,â€”,â€”,â€”,38.993575,-105.507774
7,Connecticut,"5,543","14,357","4,842","12,542",701,"1,816",171,443,530,"1,372",â€”,â€”,â€”,â€”,41.579784,-72.746667
8,Delaware,"2,489","6,446","1,949","5,047",540,"1,399",91,237,355,920,â€”,â€”,94,242,38.993550,-75.447374
9,District of Columbia,68,177,61,158,7,19,7,19,â€”,â€”,â€”,â€”,â€”,â€”,38.904148,-77.017094

In [16]:
population[['NAME', 'POPESTIMATE2019']]

                        NAME  POPESTIMATE2019
0              United States        328239523
1                    Alabama          4903185
2                     Alaska           731545
3                    Arizona          7278717
4                   Arkansas          3017804
5                 California         39512223
6                   Colorado          5758736
7                Connecticut          3565287
8                   Delaware           973764
9       District of Columbia           705749
10                   Florida         21477737
11                   Georgia         10617423
12                    Hawaii          1415872
13                     Idaho          1787065
14                  Illinois         12671821
15                   Indiana          6732219
16                      Iowa          3155070
17                    Kansas          2913314
18                  Kentucky          4467673
19                 Louisiana          4648794
20                     Maine          1344212
21                  Maryland          6045680
22             Massachusetts          6892503
23                  Michigan          9986857
24                 Minnesota          5639632
25               Mississippi          2976149
26                  Missouri          6137428
27                   Montana          1068778
28                  Nebraska          1934408
29                    Nevada          3080156
30             New Hampshire          1359711
31                New Jersey          8882190
32                New Mexico          2096829
33                  New York         19453561
34            North Carolina         10488084
35              North Dakota           762062
36                      Ohio         11689100
37                  Oklahoma          3956971
38                    Oregon          4217737
39              Pennsylvania         12801989
40              Rhode Island          1059361
41            South Carolina          5148714
42              South Dakota           884659
43                 Tennessee          6829174
44                     Texas         28995881
45                      Utah          3205958
46                   Vermont           623989
47                  Virginia          8535519
48                Washington          7614893
49             West Virginia          1792147
50                 Wisconsin          5822434
51                   Wyoming           578759
52  Puerto Rico Commonwealth          3193694

### Merge state population date with state COVID-19 data

In [17]:
state_columns=['Confirmed', 'Deaths', 'Recovered', 'Active', ]

In [18]:
state_with_population = pd.merge(state_totals[state_columns], population[['NAME', 'POPESTIMATE2019']], left_on='Province_State', right_on='NAME')
state_with_population['fraction_confirmed'] = state_with_population['Confirmed'] / state_with_population['POPESTIMATE2019'] * 100.0
state_with_population['deaths'] = state_with_population['Deaths'] / state_with_population['POPESTIMATE2019'] * 100.0
state_with_population['death_rate?'] = state_with_population['Deaths'] / state_with_population['Confirmed'] * 100.0

In [19]:
state_with_population.sort_values(by='death_rate?', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
45,235,12,0,0,Vermont,623989,0.037661,0.001923,5.106383
47,4465,198,0,0,Washington,7614893,0.058635,0.002600,4.434490
18,3540,151,0,0,Louisiana,4648794,0.076149,0.003248,4.265537
36,429,16,0,0,Oklahoma,3956971,0.010842,0.000404,3.729604
10,2651,80,0,0,Georgia,10617423,0.024968,0.000753,3.017729
7,232,6,0,0,Delaware,973764,0.023825,0.000616,2.586207
22,5488,132,0,0,Michigan,9986857,0.054952,0.001322,2.405248
37,548,13,0,0,Oregon,4217737,0.012993,0.000308,2.372263
46,890,20,0,0,Virginia,8535519,0.010427,0.000234,2.247191
16,330,7,0,0,Kansas,2913314,0.011327,0.000240,2.121212
4,5852,124,0,0,California,39512223,0.014811,0.000314,2.118934
14,1513,32,0,0,Indiana,6732219,0.022474,0.000475,2.115003
40,774,16,0,0,South Carolina,5148714,0.015033,0.000311,2.067183
17,438,9,0,0,Kentucky,4467673,0.009804,0.000201,2.054795
5,2307,47,0,0,Colorado,5758736,0.040061,0.000816,2.037278
1,102,2,0,0,Alaska,731545,0.013943,0.000273,1.960784
27,108,2,0,0,Nebraska,1934408,0.005583,0.000103,1.851852
2,919,17,0,0,Arizona,7278717,0.012626,0.000234,1.849837
24,759,14,0,0,Mississippi,2976149,0.025503,0.000470,1.844532
23,503,9,0,0,Minnesota,5639632,0.008919,0.000160,1.789264
12,281,5,0,0,Idaho,1787065,0.015724,0.000280,1.779359
35,1653,29,0,0,Ohio,11689100,0.014141,0.000248,1.754386
6,1993,34,0,0,Connecticut,3565287,0.055900,0.000954,1.705971
28,920,15,0,0,Nevada,3080156,0.029869,0.000487,1.630435
32,59648,965,0,0,New York,19453561,0.306617,0.004961,1.617825
49,1164,18,0,0,Wisconsin,5822434,0.019992,0.000309,1.546392
8,342,5,0,0,District of Columbia,705749,0.048459,0.000708,1.461988
13,4596,66,0,0,Illinois,12671821,0.036269,0.000521,1.436031
25,915,13,0,0,Missouri,6137428,0.014909,0.000212,1.420765
3,426,6,0,0,Arkansas,3017804,0.014116,0.000199,1.408451
43,2792,37,0,0,Texas,28995881,0.009629,0.000128,1.325215
9,4246,56,0,0,Florida,21477737,0.019769,0.000261,1.318888
0,825,10,0,0,Alabama,4903185,0.016826,0.000204,1.212121
30,13386,161,0,0,New Jersey,8882190,0.150706,0.001813,1.202749
38,3432,41,0,0,Pennsylvania,12801989,0.026808,0.000320,1.194639
15,336,4,0,0,Iowa,3155070,0.010650,0.000127,1.190476
19,253,3,0,0,Maine,1344212,0.018821,0.000223,1.185771
41,90,1,0,0,South Dakota,884659,0.010173,0.000113,1.111111
39,294,3,0,0,Rhode Island,1059361,0.027753,0.000283,1.020408
34,98,1,0,0,North Dakota,762062,0.012860,0.000131,1.020408
21,4955,48,0,0,Massachusetts,6892503,0.071890,0.000696,0.968718
29,214,2,0,0,New Hampshire,1359711,0.015739,0.000147,0.934579
31,237,2,0,0,New Mexico,2096829,0.011303,0.000095,0.843882
20,1239,10,0,0,Maryland,6045680,0.020494,0.000165,0.807103
26,154,1,0,0,Montana,1068778,0.014409,0.000094,0.649351
33,1191,7,0,0,North Carolina,10488084,0.011356,0.000067,0.587741
42,1720,8,0,0,Tennessee,6829174,0.025186,0.000117,0.465116
44,720,2,0,0,Utah,3205958,0.022458,0.000062,0.277778
48,113,0,0,0,West Virginia,1792147,0.006305,0.000000,0.000000
11,149,0,0,0,Hawaii,1415872,0.010524,0.000000,0.000000
50,86,0,0,0,Wyoming,578759,0.014859,0.000000,0.000000

In [20]:
state_with_population.sort_values(by='fraction_confirmed', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
32,59648,965,0,0,New York,19453561,0.306617,0.004961,1.617825
30,13386,161,0,0,New Jersey,8882190,0.150706,0.001813,1.202749
18,3540,151,0,0,Louisiana,4648794,0.076149,0.003248,4.265537
21,4955,48,0,0,Massachusetts,6892503,0.071890,0.000696,0.968718
47,4465,198,0,0,Washington,7614893,0.058635,0.002600,4.434490
6,1993,34,0,0,Connecticut,3565287,0.055900,0.000954,1.705971
22,5488,132,0,0,Michigan,9986857,0.054952,0.001322,2.405248
8,342,5,0,0,District of Columbia,705749,0.048459,0.000708,1.461988
5,2307,47,0,0,Colorado,5758736,0.040061,0.000816,2.037278
45,235,12,0,0,Vermont,623989,0.037661,0.001923,5.106383
13,4596,66,0,0,Illinois,12671821,0.036269,0.000521,1.436031
28,920,15,0,0,Nevada,3080156,0.029869,0.000487,1.630435
39,294,3,0,0,Rhode Island,1059361,0.027753,0.000283,1.020408
38,3432,41,0,0,Pennsylvania,12801989,0.026808,0.000320,1.194639
24,759,14,0,0,Mississippi,2976149,0.025503,0.000470,1.844532
42,1720,8,0,0,Tennessee,6829174,0.025186,0.000117,0.465116
10,2651,80,0,0,Georgia,10617423,0.024968,0.000753,3.017729
7,232,6,0,0,Delaware,973764,0.023825,0.000616,2.586207
14,1513,32,0,0,Indiana,6732219,0.022474,0.000475,2.115003
44,720,2,0,0,Utah,3205958,0.022458,0.000062,0.277778
20,1239,10,0,0,Maryland,6045680,0.020494,0.000165,0.807103
49,1164,18,0,0,Wisconsin,5822434,0.019992,0.000309,1.546392
9,4246,56,0,0,Florida,21477737,0.019769,0.000261,1.318888
19,253,3,0,0,Maine,1344212,0.018821,0.000223,1.185771
0,825,10,0,0,Alabama,4903185,0.016826,0.000204,1.212121
29,214,2,0,0,New Hampshire,1359711,0.015739,0.000147,0.934579
12,281,5,0,0,Idaho,1787065,0.015724,0.000280,1.779359
40,774,16,0,0,South Carolina,5148714,0.015033,0.000311,2.067183
25,915,13,0,0,Missouri,6137428,0.014909,0.000212,1.420765
50,86,0,0,0,Wyoming,578759,0.014859,0.000000,0.000000
4,5852,124,0,0,California,39512223,0.014811,0.000314,2.118934
26,154,1,0,0,Montana,1068778,0.014409,0.000094,0.649351
35,1653,29,0,0,Ohio,11689100,0.014141,0.000248,1.754386
3,426,6,0,0,Arkansas,3017804,0.014116,0.000199,1.408451
1,102,2,0,0,Alaska,731545,0.013943,0.000273,1.960784
37,548,13,0,0,Oregon,4217737,0.012993,0.000308,2.372263
34,98,1,0,0,North Dakota,762062,0.012860,0.000131,1.020408
2,919,17,0,0,Arizona,7278717,0.012626,0.000234,1.849837
33,1191,7,0,0,North Carolina,10488084,0.011356,0.000067,0.587741
16,330,7,0,0,Kansas,2913314,0.011327,0.000240,2.121212
31,237,2,0,0,New Mexico,2096829,0.011303,0.000095,0.843882
36,429,16,0,0,Oklahoma,3956971,0.010842,0.000404,3.729604
15,336,4,0,0,Iowa,3155070,0.010650,0.000127,1.190476
11,149,0,0,0,Hawaii,1415872,0.010524,0.000000,0.000000
46,890,20,0,0,Virginia,8535519,0.010427,0.000234,2.247191
41,90,1,0,0,South Dakota,884659,0.010173,0.000113,1.111111
17,438,9,0,0,Kentucky,4467673,0.009804,0.000201,2.054795
43,2792,37,0,0,Texas,28995881,0.009629,0.000128,1.325215
23,503,9,0,0,Minnesota,5639632,0.008919,0.000160,1.789264
48,113,0,0,0,West Virginia,1792147,0.006305,0.000000,0.000000
27,108,2,0,0,Nebraska,1934408,0.005583,0.000103,1.851852

In [21]:
state_with_population.sort_values(by='deaths', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
32,59648,965,0,0,New York,19453561,0.306617,0.004961,1.617825
18,3540,151,0,0,Louisiana,4648794,0.076149,0.003248,4.265537
47,4465,198,0,0,Washington,7614893,0.058635,0.002600,4.434490
45,235,12,0,0,Vermont,623989,0.037661,0.001923,5.106383
30,13386,161,0,0,New Jersey,8882190,0.150706,0.001813,1.202749
22,5488,132,0,0,Michigan,9986857,0.054952,0.001322,2.405248
6,1993,34,0,0,Connecticut,3565287,0.055900,0.000954,1.705971
5,2307,47,0,0,Colorado,5758736,0.040061,0.000816,2.037278
10,2651,80,0,0,Georgia,10617423,0.024968,0.000753,3.017729
8,342,5,0,0,District of Columbia,705749,0.048459,0.000708,1.461988
21,4955,48,0,0,Massachusetts,6892503,0.071890,0.000696,0.968718
7,232,6,0,0,Delaware,973764,0.023825,0.000616,2.586207
13,4596,66,0,0,Illinois,12671821,0.036269,0.000521,1.436031
28,920,15,0,0,Nevada,3080156,0.029869,0.000487,1.630435
14,1513,32,0,0,Indiana,6732219,0.022474,0.000475,2.115003
24,759,14,0,0,Mississippi,2976149,0.025503,0.000470,1.844532
36,429,16,0,0,Oklahoma,3956971,0.010842,0.000404,3.729604
38,3432,41,0,0,Pennsylvania,12801989,0.026808,0.000320,1.194639
4,5852,124,0,0,California,39512223,0.014811,0.000314,2.118934
40,774,16,0,0,South Carolina,5148714,0.015033,0.000311,2.067183
49,1164,18,0,0,Wisconsin,5822434,0.019992,0.000309,1.546392
37,548,13,0,0,Oregon,4217737,0.012993,0.000308,2.372263
39,294,3,0,0,Rhode Island,1059361,0.027753,0.000283,1.020408
12,281,5,0,0,Idaho,1787065,0.015724,0.000280,1.779359
1,102,2,0,0,Alaska,731545,0.013943,0.000273,1.960784
9,4246,56,0,0,Florida,21477737,0.019769,0.000261,1.318888
35,1653,29,0,0,Ohio,11689100,0.014141,0.000248,1.754386
16,330,7,0,0,Kansas,2913314,0.011327,0.000240,2.121212
46,890,20,0,0,Virginia,8535519,0.010427,0.000234,2.247191
2,919,17,0,0,Arizona,7278717,0.012626,0.000234,1.849837
19,253,3,0,0,Maine,1344212,0.018821,0.000223,1.185771
25,915,13,0,0,Missouri,6137428,0.014909,0.000212,1.420765
0,825,10,0,0,Alabama,4903185,0.016826,0.000204,1.212121
17,438,9,0,0,Kentucky,4467673,0.009804,0.000201,2.054795
3,426,6,0,0,Arkansas,3017804,0.014116,0.000199,1.408451
20,1239,10,0,0,Maryland,6045680,0.020494,0.000165,0.807103
23,503,9,0,0,Minnesota,5639632,0.008919,0.000160,1.789264
29,214,2,0,0,New Hampshire,1359711,0.015739,0.000147,0.934579
34,98,1,0,0,North Dakota,762062,0.012860,0.000131,1.020408
43,2792,37,0,0,Texas,28995881,0.009629,0.000128,1.325215
15,336,4,0,0,Iowa,3155070,0.010650,0.000127,1.190476
42,1720,8,0,0,Tennessee,6829174,0.025186,0.000117,0.465116
41,90,1,0,0,South Dakota,884659,0.010173,0.000113,1.111111
27,108,2,0,0,Nebraska,1934408,0.005583,0.000103,1.851852
31,237,2,0,0,New Mexico,2096829,0.011303,0.000095,0.843882
26,154,1,0,0,Montana,1068778,0.014409,0.000094,0.649351
33,1191,7,0,0,North Carolina,10488084,0.011356,0.000067,0.587741
44,720,2,0,0,Utah,3205958,0.022458,0.000062,0.277778
11,149,0,0,0,Hawaii,1415872,0.010524,0.000000,0.000000
48,113,0,0,0,West Virginia,1792147,0.006305,0.000000,0.000000
50,86,0,0,0,Wyoming,578759,0.014859,0.000000,0.000000

In [22]:
state_with_population.describe()

,Confirmed,Deaths,Recovered,Active,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
count,51.000000,51.000000,51.0,51.0,5.100000e+01,51.000000,51.000000,51.000000
mean,2755.901961,48.235294,0.0,0.0,6.436069e+06,0.030883,0.000567,1.667706
std,8445.276067,138.628942,0.0,0.0,7.360660e+06,0.046258,0.000898,1.047909
min,86.000000,0.000000,0.0,0.0,5.787590e+05,0.005583,0.000000,0.000000
25%,267.000000,3.500000,0.0,0.0,1.789606e+06,0.011991,0.000139,1.065760
50%,774.000000,12.000000,0.0,0.0,4.467673e+06,0.015739,0.000261,1.546392
75%,2150.000000,35.500000,0.0,0.0,7.446805e+06,0.027280,0.000504,2.060989
max,59648.000000,965.000000,0.0,0.0,3.951222e+07,0.306617,0.004961,5.106383

## Something strange about the data direct from github

In [23]:
dfx = pd.read_html(url)
dfx

[      Unnamed: 0     FIPS     Admin2  Province_State      Country_Region  \
 0            NaN  45001.0  Abbeville  South Carolina                  US
 1            NaN  22001.0     Acadia       Louisiana                  US
 2            NaN  51001.0   Accomack        Virginia                  US
 3            NaN  16001.0        Ada           Idaho                  US
 4            NaN  19001.0      Adair            Iowa                  US
 ...          ...      ...        ...             ...                 ...
 3429         NaN      NaN        NaN             NaN           Venezuela
 3430         NaN      NaN        NaN             NaN             Vietnam
 3431         NaN      NaN        NaN             NaN  West Bank and Gaza
 3432         NaN      NaN        NaN             NaN              Zambia
 3433         NaN      NaN        NaN             NaN            Zimbabwe

               Last_Update        Lat       Long_  Confirmed  Deaths  \
 0     2020-03-29 23:08:25  34.223334  -82.461707          3       0
 1     2020-03-29 23:08:25  30.295065  -92.414197          9       1
 2     2020-03-29 23:08:25  37.767072  -75.632346          3       0
 3     2020-03-29 23:08:25  43.452658 -116.241552         92       1
 4     2020-03-29 23:08:25  41.330756  -94.471059          1       0
 ...                   ...        ...         ...        ...     ...
 3429  2020-03-29 23:08:13   6.423800  -66.589700        119       2
 3430  2020-03-29 23:08:13  14.058324  108.277199        188       0
 3431  2020-03-29 23:08:13  31.952200   35.233200        109       1
 3432  2020-03-29 23:08:13 -13.133897   27.849332         29       0
 3433  2020-03-29 23:08:13 -19.015438   29.154857          7       1

       Recovered  Active                   Combined_Key
 0             0       0  Abbeville, South Carolina, US
 1             0       0          Acadia, Louisiana, US
 2             0       0         Accomack, Virginia, US
 3             0       0                 Ada, Idaho, US
 4             0       0                Adair, Iowa, US
 ...         ...     ...                            ...
 3429         39      78                      Venezuela
 3430         25     163                        Vietnam
 3431         18      90             West Bank and Gaza
 3432          0      29                         Zambia
 3433          0       6                       Zimbabwe

 [3434 rows x 13 columns]]

import datapackage
import pandas as pd

data_url = 'https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv'

# to load Data Package into storage
package = datapackage.Package(data_url)

# to load only tabular data
resources = package.resources
for resource in resources:
    if resource.tabular:
        data = pd.read_csv(resource.descriptor['path'])
        print (data)