In [1]:
import pandas as pd

In [2]:
population = pd.read_csv('data/SCPRC-EST2019-18+POP-RES.csv')

In [3]:
population.sort_values(by='POPESTIMATE2019', ascending=False).head(10)

,SUMLEV,REGION,DIVISION,STATE,NAME,POPESTIMATE2019,POPEST18PLUS2019,PCNT_POPEST18PLUS
0,10,0,0,0,United States,328239523,255200373,77.7
5,40,4,9,6,California,39512223,30617582,77.5
44,40,3,7,48,Texas,28995881,21596071,74.5
10,40,3,5,12,Florida,21477737,17247808,80.3
33,40,1,2,36,New York,19453561,15425262,79.3
39,40,1,2,42,Pennsylvania,12801989,10167376,79.4
14,40,2,3,17,Illinois,12671821,9853946,77.8
36,40,2,3,39,Ohio,11689100,9111081,77.9
11,40,3,5,13,Georgia,10617423,8113542,76.4
34,40,3,5,37,North Carolina,10488084,8187369,78.1

In [7]:
geog = pd.read_csv('data/us_geography.csv')

In [8]:
geog.head(10)

,State,tot_sq_mi,tot_sq_km,land_sq_mi,land_sq_km,water_sq_mi,water_sq_km,inland_sq_mi,inland_sq_km,coast_sq_mi,coast_sq_km,gl_sq_mi,gl_sq_km,terr_sq_mi,terr_sq_km,latitude,longitude
0,United States,"3,796,742","9,833,517","3,531,905","9,147,593","264,837","685,924","85,647","221,824","42,337","109,652","60,094","155,643","76,759","198,806",NaN,NaN
1,Alabama,"52,420","135,767","50,645","131,171","1,775","4,597","1,058","2,740",517,"1,340",—,—,199,516,32.739632,-86.843459
2,Alaska,"665,384","1,723,337","570,641","1,477,953","94,743","245,383","19,304","49,997","26,119","67,647",—,—,"49,320","127,739",63.346191,-152.837068
3,Arizona,"113,990","295,234","113,594","294,207",396,"1,026",396,"1,026",—,—,—,—,—,—,34.209964,-111.602401
4,Arkansas,"53,179","137,732","52,035","134,771","1,143","2,961","1,143","2,961",—,—,—,—,—,—,34.895526,-92.444626
5,California,"163,695","423,967","155,779","403,466","7,916","20,501","2,833","7,339",245,634,—,—,"4,837","12,528",37.148573,-119.540651
6,Colorado,"104,094","269,601","103,642","268,431",452,"1,170",452,"1,170",—,—,—,—,—,—,38.993575,-105.507774
7,Connecticut,"5,543","14,357","4,842","12,542",701,"1,816",171,443,530,"1,372",—,—,—,—,41.579784,-72.746667
8,Delaware,"2,489","6,446","1,949","5,047",540,"1,399",91,237,355,920,—,—,94,242,38.993550,-75.447374
9,District of Columbia,68,177,61,158,7,19,7,19,—,—,—,—,—,—,38.904148,-77.017094

df = pd.read_csv('https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv',
                 error_bad_lines=False)

In [ ]:
df

In [9]:
import datapackage
import pandas as pd

data_url = 'https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv'

# to load Data Package into storage
package = datapackage.Package(data_url)

# to load only tabular data
resources = package.resources
for resource in resources:
    if resource.tabular:
        data = pd.read_csv(resource.descriptor['path'])
        print (data)

DataPackageException: Unable to parse JSON at "https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv". Expecting value: line 7 column 1 (char 6)