In [1]:
import pandas as pd
import requests
pd.set_option('max_rows', 100)

In [2]:
url = 'https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-30-2020.csv'

### Get daily data from the url

In [3]:
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

r = requests.get(url, headers=header)
df = pd.read_html(r.text, header=[0], index_col=1)[0]

#### quick glance at the data

In [4]:
df[df.Country_Region=='US'].sort_values(by='Province_State')

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
1115.0,NaN,St. Clair,Alabama,US,2020-03-30 22:52:45,33.719022,-86.310294,13,0,0,0,"St. Clair, Alabama, US"
1117.0,NaN,Shelby,Alabama,US,2020-03-30 22:52:45,33.268798,-86.662326,79,0,0,0,"Shelby, Alabama, US"
1019.0,NaN,Cherokee,Alabama,US,2020-03-30 22:52:45,34.178060,-85.606390,2,0,0,0,"Cherokee, Alabama, US"
1099.0,NaN,Monroe,Alabama,US,2020-03-30 22:52:45,31.567294,-87.369950,1,0,0,0,"Monroe, Alabama, US"
1097.0,NaN,Mobile,Alabama,US,2020-03-30 22:52:45,30.784723,-88.208424,44,1,0,0,"Mobile, Alabama, US"
...,...,...,...,...,...,...,...,...,...,...,...,...
56025.0,NaN,Natrona,Wyoming,US,2020-03-30 22:52:45,42.961801,-106.797885,10,0,0,0,"Natrona, Wyoming, US"
56043.0,NaN,Washakie,Wyoming,US,2020-03-30 22:52:45,43.904516,-107.680187,1,0,0,0,"Washakie, Wyoming, US"
56023.0,NaN,Lincoln,Wyoming,US,2020-03-30 22:52:45,42.263764,-110.656400,0,0,0,0,"Lincoln, Wyoming, US"
56015.0,NaN,Goshen,Wyoming,US,2020-03-30 22:52:45,42.087982,-104.353474,1,0,0,0,"Goshen, Wyoming, US"
56021.0,NaN,Laramie,Wyoming,US,2020-03-30 22:52:45,41.307025,-104.688750,20,0,0,0,"Laramie, Wyoming, US"

In [5]:
df.describe()

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,0.0,3439.000000,3439.000000,3439.000000,3439.000000,3439.000000,3439.000000
mean,NaN,36.786233,-82.615351,227.497819,10.928177,47.852864,122.180867
std,NaN,10.217825,39.300282,3142.090662,255.755207,1200.918451,2119.112151
min,NaN,-42.882100,-170.132000,0.000000,0.000000,0.000000,-6.000000
25%,NaN,33.937972,-97.616753,0.000000,0.000000,0.000000,0.000000
50%,NaN,38.050954,-89.024527,2.000000,0.000000,0.000000,0.000000
75%,NaN,41.720212,-81.698105,12.000000,0.000000,0.000000,0.000000
max,NaN,71.706900,178.065000,101739.000000,11591.000000,62889.000000,75528.000000

### Aggregate by state

In [6]:
state_totals = df[df.Country_Region=='US'].groupby(by='Province_State').sum()

In [7]:
state_totals.describe()

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
count,59.0,59.000000,59.000000,59.000000,59.000000,59.000000,59.0
mean,0.0,2050.698623,-4918.486094,2742.491525,50.474576,95.661017,0.0
std,0.0,1723.851856,4444.368446,8878.730587,162.872211,734.786214,0.0
min,0.0,-14.271000,-25057.879425,0.000000,0.000000,0.000000,0.0
25%,0.0,561.685748,-7320.232710,174.500000,3.000000,0.000000,0.0
50%,0.0,1947.589655,-4708.049596,576.000000,10.000000,0.000000,0.0
75%,0.0,3302.767521,-1044.429181,1925.000000,35.500000,0.000000,0.0
max,0.0,8041.803434,145.673900,66663.000000,1218.000000,5644.000000,0.0

In [8]:
state_totals.sort_values(by='Confirmed', ascending=False)

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,0.0,2637.737383,-4679.399365,66663,1218,0,0
New Jersey,0.0,846.015259,-1567.071444,16636,198,0,0
California,0.0,2194.949775,-7002.258461,7138,146,0,0
Michigan,0.0,3655.617539,-7070.178085,6498,184,0,0
Massachusetts,0.0,630.994149,-1071.277031,5752,56,0,0
Florida,0.0,1939.030577,-5540.949842,5473,63,0,0
Illinois,0.0,4064.049006,-9096.189667,5056,73,0,0
Washington,0.0,1842.117670,-4708.049596,4923,205,0,0
Pennsylvania,0.0,2734.811250,-5200.226295,4155,50,0,0
Louisiana,0.0,1989.915353,-5876.747946,4025,185,0,0
Texas,0.0,8041.803434,-25057.879425,3147,45,0,0
Georgia,0.0,5216.556611,-13288.811358,2808,87,0,0
Connecticut,0.0,332.909441,-581.254637,2571,36,0,0
Colorado,0.0,2491.870366,-6751.119357,2311,47,0,0
Ohio,0.0,3547.338944,-7289.515905,1933,40,0,0
Tennessee,0.0,3409.084710,-8180.328684,1917,14,0,0
Indiana,0.0,3665.036491,-7932.108297,1786,35,0,0
Maryland,0.0,936.358097,-1840.211223,1413,15,0,0
North Carolina,0.0,3562.420971,-7950.109874,1313,7,0,0
Wisconsin,0.0,3196.450332,-6465.454559,1230,20,0,0
Arizona,0.0,505.138555,-1671.948482,1157,20,0,0
Missouri,0.0,4460.984726,-10729.940479,1051,13,0,0
Virginia,0.0,4996.297993,-10442.323661,1020,15,0,0
Nevada,0.0,667.351945,-1998.587890,1012,15,0,0
South Carolina,0.0,1562.043718,-3725.236386,925,18,0,0
Alabama,0.0,2203.246784,-5809.578199,899,10,0,0
Mississippi,0.0,2689.003578,-7350.949516,847,16,0,0
Utah,0.0,1149.410881,-3236.285569,804,4,0,0
Oregon,0.0,1601.726424,-4373.169106,606,16,0,0
Minnesota,0.0,3963.025129,-8215.492913,576,10,0,0
Oklahoma,0.0,2733.647411,-7488.357767,481,16,0,0
Kentucky,0.0,4514.657262,-10223.986874,479,11,0,0
Arkansas,0.0,2618.391704,-6932.548370,473,7,0,0
Iowa,0.0,4160.961092,-9253.086423,424,6,0,0
Rhode Island,0.0,208.275711,-357.320525,408,4,0,0
District of Columbia,0.0,38.904178,-77.016560,401,9,0,0
Kansas,0.0,4040.964784,-10298.877911,372,8,0,0
Idaho,0.0,1947.589655,-5036.245496,340,6,0,0
New Hampshire,0.0,434.789729,-715.776567,314,3,0,0
Maine,0.0,715.003014,-1112.380298,275,3,0,0
Delaware,0.0,117.327830,-226.599712,264,6,0,0
Vermont,0.0,618.232941,-1017.581330,256,12,0,0
New Mexico,0.0,1172.481604,-3601.107483,237,2,0,0
Hawaii,0.0,105.141415,-786.616182,175,0,0,0
Puerto Rico,0.0,18.220800,-66.590100,174,6,0,0
Montana,0.0,2630.582703,-6143.222113,171,5,0,0
West Virginia,0.0,2134.783954,-4433.959998,145,1,0,0
Nebraska,0.0,3842.926930,-9210.628137,145,2,0,0
Alaska,0.0,1747.579877,-4229.319334,114,3,0,0
North Dakota,0.0,2511.855857,-5313.217852,109,2,0,0
Grand Princess,0.0,0.000000,0.000000,103,3,0,0
South Dakota,0.0,2921.997865,-6554.501988,101,1,0,0
Wyoming,0.0,990.998367,-2464.524571,94,0,0,0
Guam,0.0,13.444300,144.793700,58,1,0,0
Diamond Princess,0.0,0.000000,0.000000,49,0,0,0
Northern Mariana Islands,0.0,15.097900,145.673900,0,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,5644,0
Virgin Islands,0.0,18.335800,-64.896300,0,0,0,0
American Samoa,0.0,-14.271000,-170.132000,0,0,0,0

In [9]:
state_totals.sort_values(by='Deaths', ascending=False)

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,0.0,2637.737383,-4679.399365,66663,1218,0,0
Washington,0.0,1842.117670,-4708.049596,4923,205,0,0
New Jersey,0.0,846.015259,-1567.071444,16636,198,0,0
Louisiana,0.0,1989.915353,-5876.747946,4025,185,0,0
Michigan,0.0,3655.617539,-7070.178085,6498,184,0,0
California,0.0,2194.949775,-7002.258461,7138,146,0,0
Georgia,0.0,5216.556611,-13288.811358,2808,87,0,0
Illinois,0.0,4064.049006,-9096.189667,5056,73,0,0
Florida,0.0,1939.030577,-5540.949842,5473,63,0,0
Massachusetts,0.0,630.994149,-1071.277031,5752,56,0,0
Pennsylvania,0.0,2734.811250,-5200.226295,4155,50,0,0
Colorado,0.0,2491.870366,-6751.119357,2311,47,0,0
Texas,0.0,8041.803434,-25057.879425,3147,45,0,0
Ohio,0.0,3547.338944,-7289.515905,1933,40,0,0
Connecticut,0.0,332.909441,-581.254637,2571,36,0,0
Indiana,0.0,3665.036491,-7932.108297,1786,35,0,0
Arizona,0.0,505.138555,-1671.948482,1157,20,0,0
Wisconsin,0.0,3196.450332,-6465.454559,1230,20,0,0
South Carolina,0.0,1562.043718,-3725.236386,925,18,0,0
Mississippi,0.0,2689.003578,-7350.949516,847,16,0,0
Oklahoma,0.0,2733.647411,-7488.357767,481,16,0,0
Oregon,0.0,1601.726424,-4373.169106,606,16,0,0
Nevada,0.0,667.351945,-1998.587890,1012,15,0,0
Maryland,0.0,936.358097,-1840.211223,1413,15,0,0
Virginia,0.0,4996.297993,-10442.323661,1020,15,0,0
Tennessee,0.0,3409.084710,-8180.328684,1917,14,0,0
Missouri,0.0,4460.984726,-10729.940479,1051,13,0,0
Vermont,0.0,618.232941,-1017.581330,256,12,0,0
Kentucky,0.0,4514.657262,-10223.986874,479,11,0,0
Alabama,0.0,2203.246784,-5809.578199,899,10,0,0
Minnesota,0.0,3963.025129,-8215.492913,576,10,0,0
District of Columbia,0.0,38.904178,-77.016560,401,9,0,0
Kansas,0.0,4040.964784,-10298.877911,372,8,0,0
Arkansas,0.0,2618.391704,-6932.548370,473,7,0,0
North Carolina,0.0,3562.420971,-7950.109874,1313,7,0,0
Puerto Rico,0.0,18.220800,-66.590100,174,6,0,0
Delaware,0.0,117.327830,-226.599712,264,6,0,0
Idaho,0.0,1947.589655,-5036.245496,340,6,0,0
Iowa,0.0,4160.961092,-9253.086423,424,6,0,0
Montana,0.0,2630.582703,-6143.222113,171,5,0,0
Rhode Island,0.0,208.275711,-357.320525,408,4,0,0
Utah,0.0,1149.410881,-3236.285569,804,4,0,0
Grand Princess,0.0,0.000000,0.000000,103,3,0,0
New Hampshire,0.0,434.789729,-715.776567,314,3,0,0
Maine,0.0,715.003014,-1112.380298,275,3,0,0
Alaska,0.0,1747.579877,-4229.319334,114,3,0,0
Nebraska,0.0,3842.926930,-9210.628137,145,2,0,0
North Dakota,0.0,2511.855857,-5313.217852,109,2,0,0
New Mexico,0.0,1172.481604,-3601.107483,237,2,0,0
West Virginia,0.0,2134.783954,-4433.959998,145,1,0,0
Guam,0.0,13.444300,144.793700,58,1,0,0
South Dakota,0.0,2921.997865,-6554.501988,101,1,0,0
American Samoa,0.0,-14.271000,-170.132000,0,0,0,0
Northern Mariana Islands,0.0,15.097900,145.673900,0,0,0,0
Virgin Islands,0.0,18.335800,-64.896300,0,0,0,0
Diamond Princess,0.0,0.000000,0.000000,49,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,5644,0
Hawaii,0.0,105.141415,-786.616182,175,0,0,0
Wyoming,0.0,990.998367,-2464.524571,94,0,0,0

In [10]:
df[df.Country_Region=='US'].groupby(by='Province_State').sum().sort_values(by='Deaths', ascending=False)

,Unnamed: 0,Lat,Long_,Confirmed,Deaths,Recovered,Active
Province_State,,,,,,,
New York,0.0,2637.737383,-4679.399365,66663,1218,0,0
Washington,0.0,1842.117670,-4708.049596,4923,205,0,0
New Jersey,0.0,846.015259,-1567.071444,16636,198,0,0
Louisiana,0.0,1989.915353,-5876.747946,4025,185,0,0
Michigan,0.0,3655.617539,-7070.178085,6498,184,0,0
California,0.0,2194.949775,-7002.258461,7138,146,0,0
Georgia,0.0,5216.556611,-13288.811358,2808,87,0,0
Illinois,0.0,4064.049006,-9096.189667,5056,73,0,0
Florida,0.0,1939.030577,-5540.949842,5473,63,0,0
Massachusetts,0.0,630.994149,-1071.277031,5752,56,0,0
Pennsylvania,0.0,2734.811250,-5200.226295,4155,50,0,0
Colorado,0.0,2491.870366,-6751.119357,2311,47,0,0
Texas,0.0,8041.803434,-25057.879425,3147,45,0,0
Ohio,0.0,3547.338944,-7289.515905,1933,40,0,0
Connecticut,0.0,332.909441,-581.254637,2571,36,0,0
Indiana,0.0,3665.036491,-7932.108297,1786,35,0,0
Arizona,0.0,505.138555,-1671.948482,1157,20,0,0
Wisconsin,0.0,3196.450332,-6465.454559,1230,20,0,0
South Carolina,0.0,1562.043718,-3725.236386,925,18,0,0
Mississippi,0.0,2689.003578,-7350.949516,847,16,0,0
Oklahoma,0.0,2733.647411,-7488.357767,481,16,0,0
Oregon,0.0,1601.726424,-4373.169106,606,16,0,0
Nevada,0.0,667.351945,-1998.587890,1012,15,0,0
Maryland,0.0,936.358097,-1840.211223,1413,15,0,0
Virginia,0.0,4996.297993,-10442.323661,1020,15,0,0
Tennessee,0.0,3409.084710,-8180.328684,1917,14,0,0
Missouri,0.0,4460.984726,-10729.940479,1051,13,0,0
Vermont,0.0,618.232941,-1017.581330,256,12,0,0
Kentucky,0.0,4514.657262,-10223.986874,479,11,0,0
Alabama,0.0,2203.246784,-5809.578199,899,10,0,0
Minnesota,0.0,3963.025129,-8215.492913,576,10,0,0
District of Columbia,0.0,38.904178,-77.016560,401,9,0,0
Kansas,0.0,4040.964784,-10298.877911,372,8,0,0
Arkansas,0.0,2618.391704,-6932.548370,473,7,0,0
North Carolina,0.0,3562.420971,-7950.109874,1313,7,0,0
Puerto Rico,0.0,18.220800,-66.590100,174,6,0,0
Delaware,0.0,117.327830,-226.599712,264,6,0,0
Idaho,0.0,1947.589655,-5036.245496,340,6,0,0
Iowa,0.0,4160.961092,-9253.086423,424,6,0,0
Montana,0.0,2630.582703,-6143.222113,171,5,0,0
Rhode Island,0.0,208.275711,-357.320525,408,4,0,0
Utah,0.0,1149.410881,-3236.285569,804,4,0,0
Grand Princess,0.0,0.000000,0.000000,103,3,0,0
New Hampshire,0.0,434.789729,-715.776567,314,3,0,0
Maine,0.0,715.003014,-1112.380298,275,3,0,0
Alaska,0.0,1747.579877,-4229.319334,114,3,0,0
Nebraska,0.0,3842.926930,-9210.628137,145,2,0,0
North Dakota,0.0,2511.855857,-5313.217852,109,2,0,0
New Mexico,0.0,1172.481604,-3601.107483,237,2,0,0
West Virginia,0.0,2134.783954,-4433.959998,145,1,0,0
Guam,0.0,13.444300,144.793700,58,1,0,0
South Dakota,0.0,2921.997865,-6554.501988,101,1,0,0
American Samoa,0.0,-14.271000,-170.132000,0,0,0,0
Northern Mariana Islands,0.0,15.097900,145.673900,0,0,0,0
Virgin Islands,0.0,18.335800,-64.896300,0,0,0,0
Diamond Princess,0.0,0.000000,0.000000,49,0,0,0
Recovered,0.0,0.000000,0.000000,0,0,5644,0
Hawaii,0.0,105.141415,-786.616182,175,0,0,0
Wyoming,0.0,990.998367,-2464.524571,94,0,0,0

In [11]:
df[df.Province_State=='New Jersey'].sort_values(by='Confirmed', ascending=False)

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
NaN,NaN,Unassigned,New Jersey,US,2020-03-30 22:52:45,0.000000,0.000000,3847,91,0,0,"Unassigned, New Jersey, US"
34003.0,NaN,Bergen,New Jersey,US,2020-03-30 22:52:45,40.960109,-74.071643,2482,23,0,0,"Bergen, New Jersey, US"
34013.0,NaN,Essex,New Jersey,US,2020-03-30 22:52:45,40.786813,-74.246580,1564,13,0,0,"Essex, New Jersey, US"
34017.0,NaN,Hudson,New Jersey,US,2020-03-30 22:52:45,40.737662,-74.075157,1314,7,0,0,"Hudson, New Jersey, US"
34039.0,NaN,Union,New Jersey,US,2020-03-30 22:52:45,40.658354,-74.306801,1213,7,0,0,"Union, New Jersey, US"
34023.0,NaN,Middlesex,New Jersey,US,2020-03-30 22:52:45,40.436299,-74.414270,1123,12,0,0,"Middlesex, New Jersey, US"
34031.0,NaN,Passaic,New Jersey,US,2020-03-30 22:52:45,41.032386,-74.299541,1091,10,0,0,"Passaic, New Jersey, US"
34025.0,NaN,Monmouth,New Jersey,US,2020-03-30 22:52:45,40.265497,-74.222407,1030,8,0,0,"Monmouth, New Jersey, US"
34029.0,NaN,Ocean,New Jersey,US,2020-03-30 22:52:45,39.889545,-74.280893,874,6,0,0,"Ocean, New Jersey, US"
34027.0,NaN,Morris,New Jersey,US,2020-03-30 22:52:45,40.860953,-74.545537,720,8,0,0,"Morris, New Jersey, US"
34035.0,NaN,Somerset,New Jersey,US,2020-03-30 22:52:45,40.564657,-74.616830,349,6,0,0,"Somerset, New Jersey, US"
34021.0,NaN,Mercer,New Jersey,US,2020-03-30 22:52:45,40.280470,-74.704796,249,0,0,0,"Mercer, New Jersey, US"
34007.0,NaN,Camden,New Jersey,US,2020-03-30 22:52:45,39.803438,-74.963888,200,1,0,0,"Camden, New Jersey, US"
34005.0,NaN,Burlington,New Jersey,US,2020-03-30 22:52:45,39.876811,-74.669278,178,2,0,0,"Burlington, New Jersey, US"
34037.0,NaN,Sussex,New Jersey,US,2020-03-30 22:52:45,41.138916,-74.691182,113,1,0,0,"Sussex, New Jersey, US"
34015.0,NaN,Gloucester,New Jersey,US,2020-03-30 22:52:45,39.715811,-75.139955,89,1,0,0,"Gloucester, New Jersey, US"
34019.0,NaN,Hunterdon,New Jersey,US,2020-03-30 22:52:45,40.563352,-74.912842,79,0,0,0,"Hunterdon, New Jersey, US"
34041.0,NaN,Warren,New Jersey,US,2020-03-30 22:52:45,40.859518,-74.995565,68,1,0,0,"Warren, New Jersey, US"
34001.0,NaN,Atlantic,New Jersey,US,2020-03-30 22:52:45,39.475387,-74.658485,29,0,0,0,"Atlantic, New Jersey, US"
34011.0,NaN,Cumberland,New Jersey,US,2020-03-30 22:52:45,39.371994,-75.107126,12,1,0,0,"Cumberland, New Jersey, US"
34009.0,NaN,Cape May,New Jersey,US,2020-03-30 22:52:45,39.150088,-74.801702,9,0,0,0,"Cape May, New Jersey, US"
34033.0,NaN,Salem,New Jersey,US,2020-03-30 22:52:45,39.587197,-75.346966,3,0,0,0,"Salem, New Jersey, US"

In [12]:
df[df.Province_State=='New Jersey'].sort_values(by='Deaths', ascending=False)

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
NaN,NaN,Unassigned,New Jersey,US,2020-03-30 22:52:45,0.000000,0.000000,3847,91,0,0,"Unassigned, New Jersey, US"
34003.0,NaN,Bergen,New Jersey,US,2020-03-30 22:52:45,40.960109,-74.071643,2482,23,0,0,"Bergen, New Jersey, US"
34013.0,NaN,Essex,New Jersey,US,2020-03-30 22:52:45,40.786813,-74.246580,1564,13,0,0,"Essex, New Jersey, US"
34023.0,NaN,Middlesex,New Jersey,US,2020-03-30 22:52:45,40.436299,-74.414270,1123,12,0,0,"Middlesex, New Jersey, US"
34031.0,NaN,Passaic,New Jersey,US,2020-03-30 22:52:45,41.032386,-74.299541,1091,10,0,0,"Passaic, New Jersey, US"
34027.0,NaN,Morris,New Jersey,US,2020-03-30 22:52:45,40.860953,-74.545537,720,8,0,0,"Morris, New Jersey, US"
34025.0,NaN,Monmouth,New Jersey,US,2020-03-30 22:52:45,40.265497,-74.222407,1030,8,0,0,"Monmouth, New Jersey, US"
34039.0,NaN,Union,New Jersey,US,2020-03-30 22:52:45,40.658354,-74.306801,1213,7,0,0,"Union, New Jersey, US"
34017.0,NaN,Hudson,New Jersey,US,2020-03-30 22:52:45,40.737662,-74.075157,1314,7,0,0,"Hudson, New Jersey, US"
34035.0,NaN,Somerset,New Jersey,US,2020-03-30 22:52:45,40.564657,-74.616830,349,6,0,0,"Somerset, New Jersey, US"
34029.0,NaN,Ocean,New Jersey,US,2020-03-30 22:52:45,39.889545,-74.280893,874,6,0,0,"Ocean, New Jersey, US"
34005.0,NaN,Burlington,New Jersey,US,2020-03-30 22:52:45,39.876811,-74.669278,178,2,0,0,"Burlington, New Jersey, US"
34037.0,NaN,Sussex,New Jersey,US,2020-03-30 22:52:45,41.138916,-74.691182,113,1,0,0,"Sussex, New Jersey, US"
34041.0,NaN,Warren,New Jersey,US,2020-03-30 22:52:45,40.859518,-74.995565,68,1,0,0,"Warren, New Jersey, US"
34015.0,NaN,Gloucester,New Jersey,US,2020-03-30 22:52:45,39.715811,-75.139955,89,1,0,0,"Gloucester, New Jersey, US"
34011.0,NaN,Cumberland,New Jersey,US,2020-03-30 22:52:45,39.371994,-75.107126,12,1,0,0,"Cumberland, New Jersey, US"
34007.0,NaN,Camden,New Jersey,US,2020-03-30 22:52:45,39.803438,-74.963888,200,1,0,0,"Camden, New Jersey, US"
34021.0,NaN,Mercer,New Jersey,US,2020-03-30 22:52:45,40.280470,-74.704796,249,0,0,0,"Mercer, New Jersey, US"
34019.0,NaN,Hunterdon,New Jersey,US,2020-03-30 22:52:45,40.563352,-74.912842,79,0,0,0,"Hunterdon, New Jersey, US"
34033.0,NaN,Salem,New Jersey,US,2020-03-30 22:52:45,39.587197,-75.346966,3,0,0,0,"Salem, New Jersey, US"
34009.0,NaN,Cape May,New Jersey,US,2020-03-30 22:52:45,39.150088,-74.801702,9,0,0,0,"Cape May, New Jersey, US"
34001.0,NaN,Atlantic,New Jersey,US,2020-03-30 22:52:45,39.475387,-74.658485,29,0,0,0,"Atlantic, New Jersey, US"

In [13]:
df[df.Province_State=='New York'].sort_values(by='Confirmed')

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
36123.0,NaN,Yates,New York,US,2020-03-30 22:52:45,42.635055,-77.103699,0,0,0,0,"Yates, New York, US"
36081.0,NaN,Queens,New York,US,2020-03-30 22:52:45,40.710881,-73.816847,0,0,0,0,"Queens, New York, US"
36099.0,NaN,Seneca,New York,US,2020-03-30 22:52:45,42.780810,-76.824971,0,0,0,0,"Seneca, New York, US"
NaN,NaN,Unassigned,New York,US,2020-03-30 22:52:45,0.000000,0.000000,0,298,0,0,"Unassigned, New York, US"
36049.0,NaN,Lewis,New York,US,2020-03-30 22:52:45,43.784416,-75.449040,0,0,0,0,"Lewis, New York, US"
36047.0,NaN,Kings,New York,US,2020-03-30 22:52:45,40.636182,-73.949356,0,0,0,0,"Kings, New York, US"
36085.0,NaN,Richmond,New York,US,2020-03-30 22:52:45,40.585822,-74.148086,0,0,0,0,"Richmond, New York, US"
36005.0,NaN,Bronx,New York,US,2020-03-30 22:52:45,40.852093,-73.862828,0,0,0,0,"Bronx, New York, US"
36035.0,NaN,Fulton,New York,US,2020-03-30 22:52:45,43.113639,-74.417988,1,0,0,0,"Fulton, New York, US"
36097.0,NaN,Schuyler,New York,US,2020-03-30 22:52:45,42.391840,-76.877330,2,0,0,0,"Schuyler, New York, US"
36041.0,NaN,Hamilton,New York,US,2020-03-30 22:52:45,43.661466,-74.497220,2,0,0,0,"Hamilton, New York, US"
36011.0,NaN,Cayuga,New York,US,2020-03-30 22:52:45,42.912617,-76.557316,3,0,0,0,"Cayuga, New York, US"
36073.0,NaN,Orleans,New York,US,2020-03-30 22:52:45,43.251698,-78.232007,4,0,0,0,"Orleans, New York, US"
36031.0,NaN,Essex,New York,US,2020-03-30 22:52:45,44.116308,-73.772978,5,0,0,0,"Essex, New York, US"
36095.0,NaN,Schoharie,New York,US,2020-03-30 22:52:45,42.588317,-74.443390,6,0,0,0,"Schoharie, New York, US"
36033.0,NaN,Franklin,New York,US,2020-03-30 22:52:45,44.590409,-74.299260,6,0,0,0,"Franklin, New York, US"
36009.0,NaN,Cattaraugus,New York,US,2020-03-30 22:52:45,42.247782,-78.679231,6,0,0,0,"Cattaraugus, New York, US"
36057.0,NaN,Montgomery,New York,US,2020-03-30 22:52:45,42.901235,-74.440116,6,0,0,0,"Montgomery, New York, US"
36107.0,NaN,Tioga,New York,US,2020-03-30 22:52:45,42.168528,-76.308358,7,0,0,0,"Tioga, New York, US"
36003.0,NaN,Allegany,New York,US,2020-03-30 22:52:45,42.257484,-78.027505,7,0,0,0,"Allegany, New York, US"
36013.0,NaN,Chautauqua,New York,US,2020-03-30 22:52:45,42.227692,-79.366918,7,0,0,0,"Chautauqua, New York, US"
36121.0,NaN,Wyoming,New York,US,2020-03-30 22:52:45,42.701451,-78.221996,8,1,0,0,"Wyoming, New York, US"
36037.0,NaN,Genesee,New York,US,2020-03-30 22:52:45,43.002260,-78.191352,9,0,0,0,"Genesee, New York, US"
36115.0,NaN,Washington,New York,US,2020-03-30 22:52:45,43.311538,-73.430434,9,0,0,0,"Washington, New York, US"
36039.0,NaN,Greene,New York,US,2020-03-30 22:52:45,42.275797,-74.123849,10,0,0,0,"Greene, New York, US"
36023.0,NaN,Cortland,New York,US,2020-03-30 22:52:45,42.595092,-76.070489,10,0,0,0,"Cortland, New York, US"
36025.0,NaN,Delaware,New York,US,2020-03-30 22:52:45,42.198376,-74.967093,11,0,0,0,"Delaware, New York, US"
36045.0,NaN,Jefferson,New York,US,2020-03-30 22:52:45,44.042010,-75.946535,11,0,0,0,"Jefferson, New York, US"
36043.0,NaN,Herkimer,New York,US,2020-03-30 22:52:45,43.420342,-74.961453,12,2,0,0,"Herkimer, New York, US"
36051.0,NaN,Livingston,New York,US,2020-03-30 22:52:45,42.725963,-77.779662,13,0,0,0,"Livingston, New York, US"
36089.0,NaN,St. Lawrence,New York,US,2020-03-30 22:52:45,44.497618,-75.065500,13,0,0,0,"St. Lawrence, New York, US"
36117.0,NaN,Wayne,New York,US,2020-03-30 22:52:45,43.154944,-77.029765,15,0,0,0,"Wayne, New York, US"
36075.0,NaN,Oswego,New York,US,2020-03-30 22:52:45,43.427789,-76.146352,15,0,0,0,"Oswego, New York, US"
36015.0,NaN,Chemung,New York,US,2020-03-30 22:52:45,42.138911,-76.763880,15,0,0,0,"Chemung, New York, US"
36077.0,NaN,Otsego,New York,US,2020-03-30 22:52:45,42.634926,-75.031514,17,1,0,0,"Otsego, New York, US"
36019.0,NaN,Clinton,New York,US,2020-03-30 22:52:45,44.745309,-73.678754,17,0,0,0,"Clinton, New York, US"
36017.0,NaN,Chenango,New York,US,2020-03-30 22:52:45,42.494300,-75.608876,17,0,0,0,"Chenango, New York, US"
36113.0,NaN,Warren,New York,US,2020-03-30 22:52:45,43.561730,-73.843370,18,0,0,0,"Warren, New York, US"
36101.0,NaN,Steuben,New York,US,2020-03-30 22:52:45,42.268914,-77.382992,19,0,0,0,"Steuben, New York, US"
36069.0,NaN,Ontario,New York,US,2020-03-30 22:52:45,42.851457,-77.308744,20,0,0,0,"Ontario, New York, US"
36065.0,NaN,Oneida,New York,US,2020-03-30 22:52:45,43.243754,-75.437104,34,0,0,0,"Oneida, New York, US"
36007.0,NaN,Broome,New York,US,2020-03-30 22:52:45,42.159032,-75.813261,35,3,0,0,"Broome, New York, US"
36021.0,NaN,Columbia,New York,US,2020-03-30 22:52:45,42.248193,-73.630891,36,1,0,0,"Columbia, New York, US"
36063.0,NaN,Niagara,New York,US,2020-03-30 22:52:45,43.198980,-78.747774,41,0,0,0,"Niagara, New York, US"
36053.0,NaN,Madison,New York,US,2020-03-30 22:52:45,42.916539,-75.672666,42,1,0,0,"Madison, New York, US"
36083.0,NaN,Rensselaer,New York,US,2020-03-30 22:52:45,42.713481,-73.510899,52,0,0,0,"Rensselaer, New York, US"
36109.0,NaN,Tompkins,New York,US,2020-03-30 22:52:45,42.449458,-76.472298,70,0,0,0,"Tompkins, New York, US"
36093.0,NaN,Schenectady,New York,US,2020-03-30 22:52:45,42.816688,-74.052783,80,1,0,0,"Schenectady, New York, US"
36105.0,NaN,Sullivan,New York,US,2020-03-30 22:52:45,41.715795,-74.763946,101,0,0,0,"Sullivan, New York, US"
36091.0,NaN,Saratoga,New York,US,2020-03-30 22:52:45,43.109042,-73.866539,108,1,0,0,"Saratoga, New York, US"
36079.0,NaN,Putnam,New York,US,2020-03-30 22:52:45,41.426301,-73.749655,167,0,0,0,"Putnam, New York, US"
36111.0,NaN,Ulster,New York,US,2020-03-30 22:52:45,41.890279,-74.262521,190,0,0,0,"Ulster, New York, US"
36001.0,NaN,Albany,New York,US,2020-03-30 22:52:45,42.600603,-73.977239,217,1,0,0,"Albany, New York, US"
36067.0,NaN,Onondaga,New York,US,2020-03-30 22:52:45,43.004919,-76.199712,228,1,0,0,"Onondaga, New York, US"
36055.0,NaN,Monroe,New York,US,2020-03-30 22:52:45,43.146389,-77.693229,246,6,0,0,"Monroe, New York, US"
36027.0,NaN,Dutchess,New York,US,2020-03-30 22:52:45,41.764861,-73.743567,392,2,0,0,"Dutchess, New York, US"
36029.0,NaN,Erie,New York,US,2020-03-30 22:52:45,42.762490,-78.730637,443,7,0,0,"Erie, New York, US"
36071.0,NaN,Orange,New York,US,2020-03-30 22:52:45,41.403375,-74.302408,1435,5,0,0,"Orange, New York, US"
36087.0,NaN,Rockland,New York,US,2020-03-30 22:52:45,41.150279,-74.025605,2511,8,0,0,"Rockland, New York, US"
36103.0,NaN,Suffolk,New York,US,2020-03-30 22:52:45,40.883201,-72.801217,5791,40,0,0,"Suffolk, New York, US"
36059.0,NaN,Nassau,New York,US,2020-03-30 22:52:45,40.740665,-73.589419,7344,39,0,0,"Nassau, New York, US"
36119.0,NaN,Westchester,New York,US,2020-03-30 22:52:45,41.162784,-73.757417,9326,10,0,0,"Westchester, New York, US"
36061.0,NaN,New York City,New York,US,2020-03-30 22:52:45,40.767273,-73.971526,37453,790,0,0,"New York City, New York, US"

In [14]:
df[df.Province_State=='New York'].sort_values(by='Confirmed')

,Unnamed: 0,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
FIPS,,,,,,,,,,,,
36123.0,NaN,Yates,New York,US,2020-03-30 22:52:45,42.635055,-77.103699,0,0,0,0,"Yates, New York, US"
36081.0,NaN,Queens,New York,US,2020-03-30 22:52:45,40.710881,-73.816847,0,0,0,0,"Queens, New York, US"
36099.0,NaN,Seneca,New York,US,2020-03-30 22:52:45,42.780810,-76.824971,0,0,0,0,"Seneca, New York, US"
NaN,NaN,Unassigned,New York,US,2020-03-30 22:52:45,0.000000,0.000000,0,298,0,0,"Unassigned, New York, US"
36049.0,NaN,Lewis,New York,US,2020-03-30 22:52:45,43.784416,-75.449040,0,0,0,0,"Lewis, New York, US"
36047.0,NaN,Kings,New York,US,2020-03-30 22:52:45,40.636182,-73.949356,0,0,0,0,"Kings, New York, US"
36085.0,NaN,Richmond,New York,US,2020-03-30 22:52:45,40.585822,-74.148086,0,0,0,0,"Richmond, New York, US"
36005.0,NaN,Bronx,New York,US,2020-03-30 22:52:45,40.852093,-73.862828,0,0,0,0,"Bronx, New York, US"
36035.0,NaN,Fulton,New York,US,2020-03-30 22:52:45,43.113639,-74.417988,1,0,0,0,"Fulton, New York, US"
36097.0,NaN,Schuyler,New York,US,2020-03-30 22:52:45,42.391840,-76.877330,2,0,0,0,"Schuyler, New York, US"
36041.0,NaN,Hamilton,New York,US,2020-03-30 22:52:45,43.661466,-74.497220,2,0,0,0,"Hamilton, New York, US"
36011.0,NaN,Cayuga,New York,US,2020-03-30 22:52:45,42.912617,-76.557316,3,0,0,0,"Cayuga, New York, US"
36073.0,NaN,Orleans,New York,US,2020-03-30 22:52:45,43.251698,-78.232007,4,0,0,0,"Orleans, New York, US"
36031.0,NaN,Essex,New York,US,2020-03-30 22:52:45,44.116308,-73.772978,5,0,0,0,"Essex, New York, US"
36095.0,NaN,Schoharie,New York,US,2020-03-30 22:52:45,42.588317,-74.443390,6,0,0,0,"Schoharie, New York, US"
36033.0,NaN,Franklin,New York,US,2020-03-30 22:52:45,44.590409,-74.299260,6,0,0,0,"Franklin, New York, US"
36009.0,NaN,Cattaraugus,New York,US,2020-03-30 22:52:45,42.247782,-78.679231,6,0,0,0,"Cattaraugus, New York, US"
36057.0,NaN,Montgomery,New York,US,2020-03-30 22:52:45,42.901235,-74.440116,6,0,0,0,"Montgomery, New York, US"
36107.0,NaN,Tioga,New York,US,2020-03-30 22:52:45,42.168528,-76.308358,7,0,0,0,"Tioga, New York, US"
36003.0,NaN,Allegany,New York,US,2020-03-30 22:52:45,42.257484,-78.027505,7,0,0,0,"Allegany, New York, US"
36013.0,NaN,Chautauqua,New York,US,2020-03-30 22:52:45,42.227692,-79.366918,7,0,0,0,"Chautauqua, New York, US"
36121.0,NaN,Wyoming,New York,US,2020-03-30 22:52:45,42.701451,-78.221996,8,1,0,0,"Wyoming, New York, US"
36037.0,NaN,Genesee,New York,US,2020-03-30 22:52:45,43.002260,-78.191352,9,0,0,0,"Genesee, New York, US"
36115.0,NaN,Washington,New York,US,2020-03-30 22:52:45,43.311538,-73.430434,9,0,0,0,"Washington, New York, US"
36039.0,NaN,Greene,New York,US,2020-03-30 22:52:45,42.275797,-74.123849,10,0,0,0,"Greene, New York, US"
36023.0,NaN,Cortland,New York,US,2020-03-30 22:52:45,42.595092,-76.070489,10,0,0,0,"Cortland, New York, US"
36025.0,NaN,Delaware,New York,US,2020-03-30 22:52:45,42.198376,-74.967093,11,0,0,0,"Delaware, New York, US"
36045.0,NaN,Jefferson,New York,US,2020-03-30 22:52:45,44.042010,-75.946535,11,0,0,0,"Jefferson, New York, US"
36043.0,NaN,Herkimer,New York,US,2020-03-30 22:52:45,43.420342,-74.961453,12,2,0,0,"Herkimer, New York, US"
36051.0,NaN,Livingston,New York,US,2020-03-30 22:52:45,42.725963,-77.779662,13,0,0,0,"Livingston, New York, US"
36089.0,NaN,St. Lawrence,New York,US,2020-03-30 22:52:45,44.497618,-75.065500,13,0,0,0,"St. Lawrence, New York, US"
36117.0,NaN,Wayne,New York,US,2020-03-30 22:52:45,43.154944,-77.029765,15,0,0,0,"Wayne, New York, US"
36075.0,NaN,Oswego,New York,US,2020-03-30 22:52:45,43.427789,-76.146352,15,0,0,0,"Oswego, New York, US"
36015.0,NaN,Chemung,New York,US,2020-03-30 22:52:45,42.138911,-76.763880,15,0,0,0,"Chemung, New York, US"
36077.0,NaN,Otsego,New York,US,2020-03-30 22:52:45,42.634926,-75.031514,17,1,0,0,"Otsego, New York, US"
36019.0,NaN,Clinton,New York,US,2020-03-30 22:52:45,44.745309,-73.678754,17,0,0,0,"Clinton, New York, US"
36017.0,NaN,Chenango,New York,US,2020-03-30 22:52:45,42.494300,-75.608876,17,0,0,0,"Chenango, New York, US"
36113.0,NaN,Warren,New York,US,2020-03-30 22:52:45,43.561730,-73.843370,18,0,0,0,"Warren, New York, US"
36101.0,NaN,Steuben,New York,US,2020-03-30 22:52:45,42.268914,-77.382992,19,0,0,0,"Steuben, New York, US"
36069.0,NaN,Ontario,New York,US,2020-03-30 22:52:45,42.851457,-77.308744,20,0,0,0,"Ontario, New York, US"
36065.0,NaN,Oneida,New York,US,2020-03-30 22:52:45,43.243754,-75.437104,34,0,0,0,"Oneida, New York, US"
36007.0,NaN,Broome,New York,US,2020-03-30 22:52:45,42.159032,-75.813261,35,3,0,0,"Broome, New York, US"
36021.0,NaN,Columbia,New York,US,2020-03-30 22:52:45,42.248193,-73.630891,36,1,0,0,"Columbia, New York, US"
36063.0,NaN,Niagara,New York,US,2020-03-30 22:52:45,43.198980,-78.747774,41,0,0,0,"Niagara, New York, US"
36053.0,NaN,Madison,New York,US,2020-03-30 22:52:45,42.916539,-75.672666,42,1,0,0,"Madison, New York, US"
36083.0,NaN,Rensselaer,New York,US,2020-03-30 22:52:45,42.713481,-73.510899,52,0,0,0,"Rensselaer, New York, US"
36109.0,NaN,Tompkins,New York,US,2020-03-30 22:52:45,42.449458,-76.472298,70,0,0,0,"Tompkins, New York, US"
36093.0,NaN,Schenectady,New York,US,2020-03-30 22:52:45,42.816688,-74.052783,80,1,0,0,"Schenectady, New York, US"
36105.0,NaN,Sullivan,New York,US,2020-03-30 22:52:45,41.715795,-74.763946,101,0,0,0,"Sullivan, New York, US"
36091.0,NaN,Saratoga,New York,US,2020-03-30 22:52:45,43.109042,-73.866539,108,1,0,0,"Saratoga, New York, US"
36079.0,NaN,Putnam,New York,US,2020-03-30 22:52:45,41.426301,-73.749655,167,0,0,0,"Putnam, New York, US"
36111.0,NaN,Ulster,New York,US,2020-03-30 22:52:45,41.890279,-74.262521,190,0,0,0,"Ulster, New York, US"
36001.0,NaN,Albany,New York,US,2020-03-30 22:52:45,42.600603,-73.977239,217,1,0,0,"Albany, New York, US"
36067.0,NaN,Onondaga,New York,US,2020-03-30 22:52:45,43.004919,-76.199712,228,1,0,0,"Onondaga, New York, US"
36055.0,NaN,Monroe,New York,US,2020-03-30 22:52:45,43.146389,-77.693229,246,6,0,0,"Monroe, New York, US"
36027.0,NaN,Dutchess,New York,US,2020-03-30 22:52:45,41.764861,-73.743567,392,2,0,0,"Dutchess, New York, US"
36029.0,NaN,Erie,New York,US,2020-03-30 22:52:45,42.762490,-78.730637,443,7,0,0,"Erie, New York, US"
36071.0,NaN,Orange,New York,US,2020-03-30 22:52:45,41.403375,-74.302408,1435,5,0,0,"Orange, New York, US"
36087.0,NaN,Rockland,New York,US,2020-03-30 22:52:45,41.150279,-74.025605,2511,8,0,0,"Rockland, New York, US"
36103.0,NaN,Suffolk,New York,US,2020-03-30 22:52:45,40.883201,-72.801217,5791,40,0,0,"Suffolk, New York, US"
36059.0,NaN,Nassau,New York,US,2020-03-30 22:52:45,40.740665,-73.589419,7344,39,0,0,"Nassau, New York, US"
36119.0,NaN,Westchester,New York,US,2020-03-30 22:52:45,41.162784,-73.757417,9326,10,0,0,"Westchester, New York, US"
36061.0,NaN,New York City,New York,US,2020-03-30 22:52:45,40.767273,-73.971526,37453,790,0,0,"New York City, New York, US"

In [15]:
population = pd.read_csv('data/SCPRC-EST2019-18+POP-RES.csv')
population.sort_values(by='POPESTIMATE2019', ascending=False).head(10)

,SUMLEV,REGION,DIVISION,STATE,NAME,POPESTIMATE2019,POPEST18PLUS2019,PCNT_POPEST18PLUS
0,10,0,0,0,United States,328239523,255200373,77.7
5,40,4,9,6,California,39512223,30617582,77.5
44,40,3,7,48,Texas,28995881,21596071,74.5
10,40,3,5,12,Florida,21477737,17247808,80.3
33,40,1,2,36,New York,19453561,15425262,79.3
39,40,1,2,42,Pennsylvania,12801989,10167376,79.4
14,40,2,3,17,Illinois,12671821,9853946,77.8
36,40,2,3,39,Ohio,11689100,9111081,77.9
11,40,3,5,13,Georgia,10617423,8113542,76.4
34,40,3,5,37,North Carolina,10488084,8187369,78.1

In [16]:
geog = pd.read_csv('data/us_geography.csv')
geog.head(10)

,State,tot_sq_mi,tot_sq_km,land_sq_mi,land_sq_km,water_sq_mi,water_sq_km,inland_sq_mi,inland_sq_km,coast_sq_mi,coast_sq_km,gl_sq_mi,gl_sq_km,terr_sq_mi,terr_sq_km,latitude,longitude
0,United States,"3,796,742","9,833,517","3,531,905","9,147,593","264,837","685,924","85,647","221,824","42,337","109,652","60,094","155,643","76,759","198,806",NaN,NaN
1,Alabama,"52,420","135,767","50,645","131,171","1,775","4,597","1,058","2,740",517,"1,340",â€”,â€”,199,516,32.739632,-86.843459
2,Alaska,"665,384","1,723,337","570,641","1,477,953","94,743","245,383","19,304","49,997","26,119","67,647",â€”,â€”,"49,320","127,739",63.346191,-152.837068
3,Arizona,"113,990","295,234","113,594","294,207",396,"1,026",396,"1,026",â€”,â€”,â€”,â€”,â€”,â€”,34.209964,-111.602401
4,Arkansas,"53,179","137,732","52,035","134,771","1,143","2,961","1,143","2,961",â€”,â€”,â€”,â€”,â€”,â€”,34.895526,-92.444626
5,California,"163,695","423,967","155,779","403,466","7,916","20,501","2,833","7,339",245,634,â€”,â€”,"4,837","12,528",37.148573,-119.540651
6,Colorado,"104,094","269,601","103,642","268,431",452,"1,170",452,"1,170",â€”,â€”,â€”,â€”,â€”,â€”,38.993575,-105.507774
7,Connecticut,"5,543","14,357","4,842","12,542",701,"1,816",171,443,530,"1,372",â€”,â€”,â€”,â€”,41.579784,-72.746667
8,Delaware,"2,489","6,446","1,949","5,047",540,"1,399",91,237,355,920,â€”,â€”,94,242,38.993550,-75.447374
9,District of Columbia,68,177,61,158,7,19,7,19,â€”,â€”,â€”,â€”,â€”,â€”,38.904148,-77.017094

In [17]:
population[['NAME', 'POPESTIMATE2019']]

                        NAME  POPESTIMATE2019
0              United States        328239523
1                    Alabama          4903185
2                     Alaska           731545
3                    Arizona          7278717
4                   Arkansas          3017804
5                 California         39512223
6                   Colorado          5758736
7                Connecticut          3565287
8                   Delaware           973764
9       District of Columbia           705749
10                   Florida         21477737
11                   Georgia         10617423
12                    Hawaii          1415872
13                     Idaho          1787065
14                  Illinois         12671821
15                   Indiana          6732219
16                      Iowa          3155070
17                    Kansas          2913314
18                  Kentucky          4467673
19                 Louisiana          4648794
20                     Maine          1344212
21                  Maryland          6045680
22             Massachusetts          6892503
23                  Michigan          9986857
24                 Minnesota          5639632
25               Mississippi          2976149
26                  Missouri          6137428
27                   Montana          1068778
28                  Nebraska          1934408
29                    Nevada          3080156
30             New Hampshire          1359711
31                New Jersey          8882190
32                New Mexico          2096829
33                  New York         19453561
34            North Carolina         10488084
35              North Dakota           762062
36                      Ohio         11689100
37                  Oklahoma          3956971
38                    Oregon          4217737
39              Pennsylvania         12801989
40              Rhode Island          1059361
41            South Carolina          5148714
42              South Dakota           884659
43                 Tennessee          6829174
44                     Texas         28995881
45                      Utah          3205958
46                   Vermont           623989
47                  Virginia          8535519
48                Washington          7614893
49             West Virginia          1792147
50                 Wisconsin          5822434
51                   Wyoming           578759
52  Puerto Rico Commonwealth          3193694

### Merge state population date with state COVID-19 data

In [18]:
state_columns=['Confirmed', 'Deaths', 'Recovered', 'Active', ]

In [19]:
state_with_population = pd.merge(state_totals[state_columns], population[['NAME', 'POPESTIMATE2019']], left_on='Province_State', right_on='NAME')
state_with_population['fraction_confirmed'] = state_with_population['Confirmed'] / state_with_population['POPESTIMATE2019'] * 100.0
state_with_population['deaths'] = state_with_population['Deaths'] / state_with_population['POPESTIMATE2019'] * 100.0
state_with_population['death_rate?'] = state_with_population['Deaths'] / state_with_population['Confirmed'] * 100.0

In [20]:
state_with_population.sort_values(by='death_rate?', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
45,256,12,0,0,Vermont,623989,0.041026,0.001923,4.687500
18,4025,185,0,0,Louisiana,4648794,0.086582,0.003980,4.596273
47,4923,205,0,0,Washington,7614893,0.064650,0.002692,4.164128
36,481,16,0,0,Oklahoma,3956971,0.012156,0.000404,3.326403
10,2808,87,0,0,Georgia,10617423,0.026447,0.000819,3.098291
26,171,5,0,0,Montana,1068778,0.016000,0.000468,2.923977
22,6498,184,0,0,Michigan,9986857,0.065066,0.001842,2.831641
37,606,16,0,0,Oregon,4217737,0.014368,0.000379,2.640264
1,114,3,0,0,Alaska,731545,0.015583,0.000410,2.631579
17,479,11,0,0,Kentucky,4467673,0.010721,0.000246,2.296451
7,264,6,0,0,Delaware,973764,0.027111,0.000616,2.272727
8,401,9,0,0,District of Columbia,705749,0.056819,0.001275,2.244389
16,372,8,0,0,Kansas,2913314,0.012769,0.000275,2.150538
35,1933,40,0,0,Ohio,11689100,0.016537,0.000342,2.069322
4,7138,146,0,0,California,39512223,0.018065,0.000370,2.045391
5,2311,47,0,0,Colorado,5758736,0.040130,0.000816,2.033752
14,1786,35,0,0,Indiana,6732219,0.026529,0.000520,1.959686
40,925,18,0,0,South Carolina,5148714,0.017966,0.000350,1.945946
24,847,16,0,0,Mississippi,2976149,0.028460,0.000538,1.889020
34,109,2,0,0,North Dakota,762062,0.014303,0.000262,1.834862
32,66663,1218,0,0,New York,19453561,0.342678,0.006261,1.827100
12,340,6,0,0,Idaho,1787065,0.019026,0.000336,1.764706
23,576,10,0,0,Minnesota,5639632,0.010213,0.000177,1.736111
2,1157,20,0,0,Arizona,7278717,0.015896,0.000275,1.728608
49,1230,20,0,0,Wisconsin,5822434,0.021125,0.000343,1.626016
28,1012,15,0,0,Nevada,3080156,0.032855,0.000487,1.482213
3,473,7,0,0,Arkansas,3017804,0.015674,0.000232,1.479915
46,1020,15,0,0,Virginia,8535519,0.011950,0.000176,1.470588
13,5056,73,0,0,Illinois,12671821,0.039900,0.000576,1.443829
43,3147,45,0,0,Texas,28995881,0.010853,0.000155,1.429933
15,424,6,0,0,Iowa,3155070,0.013439,0.000190,1.415094
6,2571,36,0,0,Connecticut,3565287,0.072112,0.001010,1.400233
27,145,2,0,0,Nebraska,1934408,0.007496,0.000103,1.379310
25,1051,13,0,0,Missouri,6137428,0.017124,0.000212,1.236917
38,4155,50,0,0,Pennsylvania,12801989,0.032456,0.000391,1.203369
30,16636,198,0,0,New Jersey,8882190,0.187296,0.002229,1.190190
9,5473,63,0,0,Florida,21477737,0.025482,0.000293,1.151105
0,899,10,0,0,Alabama,4903185,0.018335,0.000204,1.112347
19,275,3,0,0,Maine,1344212,0.020458,0.000223,1.090909
20,1413,15,0,0,Maryland,6045680,0.023372,0.000248,1.061571
41,101,1,0,0,South Dakota,884659,0.011417,0.000113,0.990099
39,408,4,0,0,Rhode Island,1059361,0.038514,0.000378,0.980392
21,5752,56,0,0,Massachusetts,6892503,0.083453,0.000812,0.973574
29,314,3,0,0,New Hampshire,1359711,0.023093,0.000221,0.955414
31,237,2,0,0,New Mexico,2096829,0.011303,0.000095,0.843882
42,1917,14,0,0,Tennessee,6829174,0.028071,0.000205,0.730308
48,145,1,0,0,West Virginia,1792147,0.008091,0.000056,0.689655
33,1313,7,0,0,North Carolina,10488084,0.012519,0.000067,0.533130
44,804,4,0,0,Utah,3205958,0.025078,0.000125,0.497512
11,175,0,0,0,Hawaii,1415872,0.012360,0.000000,0.000000
50,94,0,0,0,Wyoming,578759,0.016242,0.000000,0.000000

In [21]:
state_with_population.sort_values(by='fraction_confirmed', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
32,66663,1218,0,0,New York,19453561,0.342678,0.006261,1.827100
30,16636,198,0,0,New Jersey,8882190,0.187296,0.002229,1.190190
18,4025,185,0,0,Louisiana,4648794,0.086582,0.003980,4.596273
21,5752,56,0,0,Massachusetts,6892503,0.083453,0.000812,0.973574
6,2571,36,0,0,Connecticut,3565287,0.072112,0.001010,1.400233
22,6498,184,0,0,Michigan,9986857,0.065066,0.001842,2.831641
47,4923,205,0,0,Washington,7614893,0.064650,0.002692,4.164128
8,401,9,0,0,District of Columbia,705749,0.056819,0.001275,2.244389
45,256,12,0,0,Vermont,623989,0.041026,0.001923,4.687500
5,2311,47,0,0,Colorado,5758736,0.040130,0.000816,2.033752
13,5056,73,0,0,Illinois,12671821,0.039900,0.000576,1.443829
39,408,4,0,0,Rhode Island,1059361,0.038514,0.000378,0.980392
28,1012,15,0,0,Nevada,3080156,0.032855,0.000487,1.482213
38,4155,50,0,0,Pennsylvania,12801989,0.032456,0.000391,1.203369
24,847,16,0,0,Mississippi,2976149,0.028460,0.000538,1.889020
42,1917,14,0,0,Tennessee,6829174,0.028071,0.000205,0.730308
7,264,6,0,0,Delaware,973764,0.027111,0.000616,2.272727
14,1786,35,0,0,Indiana,6732219,0.026529,0.000520,1.959686
10,2808,87,0,0,Georgia,10617423,0.026447,0.000819,3.098291
9,5473,63,0,0,Florida,21477737,0.025482,0.000293,1.151105
44,804,4,0,0,Utah,3205958,0.025078,0.000125,0.497512
20,1413,15,0,0,Maryland,6045680,0.023372,0.000248,1.061571
29,314,3,0,0,New Hampshire,1359711,0.023093,0.000221,0.955414
49,1230,20,0,0,Wisconsin,5822434,0.021125,0.000343,1.626016
19,275,3,0,0,Maine,1344212,0.020458,0.000223,1.090909
12,340,6,0,0,Idaho,1787065,0.019026,0.000336,1.764706
0,899,10,0,0,Alabama,4903185,0.018335,0.000204,1.112347
4,7138,146,0,0,California,39512223,0.018065,0.000370,2.045391
40,925,18,0,0,South Carolina,5148714,0.017966,0.000350,1.945946
25,1051,13,0,0,Missouri,6137428,0.017124,0.000212,1.236917
35,1933,40,0,0,Ohio,11689100,0.016537,0.000342,2.069322
50,94,0,0,0,Wyoming,578759,0.016242,0.000000,0.000000
26,171,5,0,0,Montana,1068778,0.016000,0.000468,2.923977
2,1157,20,0,0,Arizona,7278717,0.015896,0.000275,1.728608
3,473,7,0,0,Arkansas,3017804,0.015674,0.000232,1.479915
1,114,3,0,0,Alaska,731545,0.015583,0.000410,2.631579
37,606,16,0,0,Oregon,4217737,0.014368,0.000379,2.640264
34,109,2,0,0,North Dakota,762062,0.014303,0.000262,1.834862
15,424,6,0,0,Iowa,3155070,0.013439,0.000190,1.415094
16,372,8,0,0,Kansas,2913314,0.012769,0.000275,2.150538
33,1313,7,0,0,North Carolina,10488084,0.012519,0.000067,0.533130
11,175,0,0,0,Hawaii,1415872,0.012360,0.000000,0.000000
36,481,16,0,0,Oklahoma,3956971,0.012156,0.000404,3.326403
46,1020,15,0,0,Virginia,8535519,0.011950,0.000176,1.470588
41,101,1,0,0,South Dakota,884659,0.011417,0.000113,0.990099
31,237,2,0,0,New Mexico,2096829,0.011303,0.000095,0.843882
43,3147,45,0,0,Texas,28995881,0.010853,0.000155,1.429933
17,479,11,0,0,Kentucky,4467673,0.010721,0.000246,2.296451
23,576,10,0,0,Minnesota,5639632,0.010213,0.000177,1.736111
48,145,1,0,0,West Virginia,1792147,0.008091,0.000056,0.689655
27,145,2,0,0,Nebraska,1934408,0.007496,0.000103,1.379310

In [22]:
state_with_population.sort_values(by='deaths', ascending=False)

,Confirmed,Deaths,Recovered,Active,NAME,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
32,66663,1218,0,0,New York,19453561,0.342678,0.006261,1.827100
18,4025,185,0,0,Louisiana,4648794,0.086582,0.003980,4.596273
47,4923,205,0,0,Washington,7614893,0.064650,0.002692,4.164128
30,16636,198,0,0,New Jersey,8882190,0.187296,0.002229,1.190190
45,256,12,0,0,Vermont,623989,0.041026,0.001923,4.687500
22,6498,184,0,0,Michigan,9986857,0.065066,0.001842,2.831641
8,401,9,0,0,District of Columbia,705749,0.056819,0.001275,2.244389
6,2571,36,0,0,Connecticut,3565287,0.072112,0.001010,1.400233
10,2808,87,0,0,Georgia,10617423,0.026447,0.000819,3.098291
5,2311,47,0,0,Colorado,5758736,0.040130,0.000816,2.033752
21,5752,56,0,0,Massachusetts,6892503,0.083453,0.000812,0.973574
7,264,6,0,0,Delaware,973764,0.027111,0.000616,2.272727
13,5056,73,0,0,Illinois,12671821,0.039900,0.000576,1.443829
24,847,16,0,0,Mississippi,2976149,0.028460,0.000538,1.889020
14,1786,35,0,0,Indiana,6732219,0.026529,0.000520,1.959686
28,1012,15,0,0,Nevada,3080156,0.032855,0.000487,1.482213
26,171,5,0,0,Montana,1068778,0.016000,0.000468,2.923977
1,114,3,0,0,Alaska,731545,0.015583,0.000410,2.631579
36,481,16,0,0,Oklahoma,3956971,0.012156,0.000404,3.326403
38,4155,50,0,0,Pennsylvania,12801989,0.032456,0.000391,1.203369
37,606,16,0,0,Oregon,4217737,0.014368,0.000379,2.640264
39,408,4,0,0,Rhode Island,1059361,0.038514,0.000378,0.980392
4,7138,146,0,0,California,39512223,0.018065,0.000370,2.045391
40,925,18,0,0,South Carolina,5148714,0.017966,0.000350,1.945946
49,1230,20,0,0,Wisconsin,5822434,0.021125,0.000343,1.626016
35,1933,40,0,0,Ohio,11689100,0.016537,0.000342,2.069322
12,340,6,0,0,Idaho,1787065,0.019026,0.000336,1.764706
9,5473,63,0,0,Florida,21477737,0.025482,0.000293,1.151105
2,1157,20,0,0,Arizona,7278717,0.015896,0.000275,1.728608
16,372,8,0,0,Kansas,2913314,0.012769,0.000275,2.150538
34,109,2,0,0,North Dakota,762062,0.014303,0.000262,1.834862
20,1413,15,0,0,Maryland,6045680,0.023372,0.000248,1.061571
17,479,11,0,0,Kentucky,4467673,0.010721,0.000246,2.296451
3,473,7,0,0,Arkansas,3017804,0.015674,0.000232,1.479915
19,275,3,0,0,Maine,1344212,0.020458,0.000223,1.090909
29,314,3,0,0,New Hampshire,1359711,0.023093,0.000221,0.955414
25,1051,13,0,0,Missouri,6137428,0.017124,0.000212,1.236917
42,1917,14,0,0,Tennessee,6829174,0.028071,0.000205,0.730308
0,899,10,0,0,Alabama,4903185,0.018335,0.000204,1.112347
15,424,6,0,0,Iowa,3155070,0.013439,0.000190,1.415094
23,576,10,0,0,Minnesota,5639632,0.010213,0.000177,1.736111
46,1020,15,0,0,Virginia,8535519,0.011950,0.000176,1.470588
43,3147,45,0,0,Texas,28995881,0.010853,0.000155,1.429933
44,804,4,0,0,Utah,3205958,0.025078,0.000125,0.497512
41,101,1,0,0,South Dakota,884659,0.011417,0.000113,0.990099
27,145,2,0,0,Nebraska,1934408,0.007496,0.000103,1.379310
31,237,2,0,0,New Mexico,2096829,0.011303,0.000095,0.843882
33,1313,7,0,0,North Carolina,10488084,0.012519,0.000067,0.533130
48,145,1,0,0,West Virginia,1792147,0.008091,0.000056,0.689655
11,175,0,0,0,Hawaii,1415872,0.012360,0.000000,0.000000
50,94,0,0,0,Wyoming,578759,0.016242,0.000000,0.000000

In [23]:
state_with_population.describe()

,Confirmed,Deaths,Recovered,Active,POPESTIMATE2019,fraction_confirmed,deaths,death_rate?
count,51.000000,51.000000,51.0,51.0,5.100000e+01,51.000000,51.000000,51.000000
mean,3165.156863,58.196078,0.0,0.0,6.436069e+06,0.035670,0.000681,1.746396
std,9492.129642,174.133744,0.0,0.0,7.360660e+06,0.052845,0.001089,1.002590
min,94.000000,0.000000,0.0,0.0,5.787590e+05,0.007496,0.000000,0.000000
25%,327.000000,5.500000,0.0,0.0,1.789606e+06,0.013871,0.000204,1.101628
50%,899.000000,14.000000,0.0,0.0,4.467673e+06,0.019026,0.000342,1.482213
75%,2441.000000,42.500000,0.0,0.0,7.446805e+06,0.032656,0.000557,2.109930
max,66663.000000,1218.000000,0.0,0.0,3.951222e+07,0.342678,0.006261,4.687500

## Something strange about the data direct from github

In [24]:
dfx = pd.read_html(url)
dfx

[      Unnamed: 0     FIPS     Admin2  Province_State      Country_Region  \
 0            NaN  45001.0  Abbeville  South Carolina                  US
 1            NaN  22001.0     Acadia       Louisiana                  US
 2            NaN  51001.0   Accomack        Virginia                  US
 3            NaN  16001.0        Ada           Idaho                  US
 4            NaN  19001.0      Adair            Iowa                  US
 ...          ...      ...        ...             ...                 ...
 3434         NaN      NaN        NaN             NaN           Venezuela
 3435         NaN      NaN        NaN             NaN             Vietnam
 3436         NaN      NaN        NaN             NaN  West Bank and Gaza
 3437         NaN      NaN        NaN             NaN              Zambia
 3438         NaN      NaN        NaN             NaN            Zimbabwe

               Last_Update        Lat       Long_  Confirmed  Deaths  \
 0     2020-03-30 22:52:45  34.223334  -82.461707          3       0
 1     2020-03-30 22:52:45  30.295065  -92.414197         11       1
 2     2020-03-30 22:52:45  37.767072  -75.632346          6       0
 3     2020-03-30 22:52:45  43.452658 -116.241552        113       2
 4     2020-03-30 22:52:45  41.330756  -94.471059          1       0
 ...                   ...        ...         ...        ...     ...
 3434  2020-03-30 22:52:33   6.423800  -66.589700        135       3
 3435  2020-03-30 22:52:33  14.058324  108.277199        203       0
 3436  2020-03-30 22:52:33  31.952200   35.233200        116       1
 3437  2020-03-30 22:52:33 -13.133897   27.849332         35       0
 3438  2020-03-30 22:52:33 -19.015438   29.154857          7       1

       Recovered  Active                   Combined_Key
 0             0       0  Abbeville, South Carolina, US
 1             0       0          Acadia, Louisiana, US
 2             0       0         Accomack, Virginia, US
 3             0       0                 Ada, Idaho, US
 4             0       0                Adair, Iowa, US
 ...         ...     ...                            ...
 3434         39      93                      Venezuela
 3435         55     148                        Vietnam
 3436         18      97             West Bank and Gaza
 3437          0      35                         Zambia
 3438          0       6                       Zimbabwe

 [3439 rows x 13 columns]]

import datapackage
import pandas as pd

data_url = 'https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports/03-27-2020.csv'

# to load Data Package into storage
package = datapackage.Package(data_url)

# to load only tabular data
resources = package.resources
for resource in resources:
    if resource.tabular:
        data = pd.read_csv(resource.descriptor['path'])
        print (data)